const T = require("./theme.js");
const { P, TITLE, H1, H2, CAP, TCAP, NUM, REFP, PB, img, table, buildDoc, write } = T;
const path = require("path");
const S2 = path.resolve(__dirname, "..", "main_study");

const c = [];

// ---------------- TITLE / ABSTRACT ----------------
c.push(TITLE("Repeated AI analyses of ecological data agree on wrong answers until the method is written down"));
c.push(P("Article type: Research Article. Target journal: Methods in Ecology and Evolution.", { size: 20, spacing: { after: 20 } }));
c.push(P("This manuscript is prepared for double-anonymous review. Author names, affiliations, the running headline, and all statements are on the separate title page.", { size: 20 }));

c.push(H1("Abstract"));
c.push(P("1. Ecologists increasingly describe a data analysis to an artificial-intelligence tool in ordinary words. The same request can return a different answer each time, and nothing in the answer shows whether it is right. We asked how often such an analysis reaches the correct value, and whether writing the method down as a reusable specification does more for it than supplying a working script."));
c.push(P("2. We assembled twelve analysis tasks on four ecological datasets, three for each of four kinds of open analytical choice, from what counts as a sampling unit to how a fitted model is set up. Each poses a question as an ecologist would ask it and has a reference value on which two independent implementations agree. Every task was run under three conditions, the question by itself, the question with a written specification, and the question with a working script for a related task, ten runs each across models from two companies, with the task as the unit of replication."));
c.push(P("3. Given the question by itself, models reached the correct value in 57 per cent of runs across all tasks, and in 2 per cent of runs on the five tasks where a choice was genuinely open. A written specification raised these figures to 90 and 78 per cent, and a working script raised the overall figure only to 72 per cent. On several tasks the runs did not scatter at random but settled on one wrong value, so that repeating the analysis or moving to another company's model returned the same error. Rewriting the analysis in a second language returned the same wrong value, and reports written from these analyses stated the same conclusions whether or not their numbers were right."));
c.push(P("4. Writing the method down changed the answer more than sharing code did, because a specification states what is to be computed while a script records how one dataset was handled. Agreement between runs was not evidence of correctness, so the two have to be checked separately. We set out what a specification needs to contain and three checks a shared collection should apply."));
c.push(P("Data and code for peer review: the tasks, reference values, prompts, run records, analysis scripts and figures are available in an anonymised repository at https://anonymous.4open.science/r/ai-skills-reproducibility-ecology-B13E/README.md.", { spacing: { before: 120 } }));
c.push(P("Keywords: analytical choices; artificial intelligence; large language models; open science; reproducibility; research software; specification; workflow provenance.", { spacing: { before: 120 } }));
c.push(PB());

// ---------------- 1 INTRODUCTION ----------------
c.push(H1("1  Introduction"));
c.push(P("Science rests on results that other people can obtain again, yet a computed result is often hard to regenerate. More than seven in ten of the researchers in one survey had failed to reproduce another group's result (Baker, 2016). Ecology shows the same pattern, and the difficulty lies mostly in the analysis rather than in the data. Fewer than a fifth of the ecology papers examined by Culina et al. (2020) could be reproduced from the code that accompanied them, and a survey of the journals of the British Ecological Society found that almost every paper shared its data while only about a third shared its code (Cooper and the BES Data and Code Hackathon Group, 2026). Even where both were available, one team reproduced the published result in between a quarter and three quarters of cases, depending on how strictly a match was judged (Kambouris et al., 2024)."));
c.push(P("Part of the difficulty has nothing to do with software. When several teams are given the same data and the same question, they reach different answers, because each makes reasonable but different analytical choices along the way (Silberzahn et al., 2018; Botvinik-Nezer et al., 2020; Breznau et al., 2022). The same spread has now been shown for ecological and evolutionary data (Gould et al., 2025). Work on analytical flexibility describes why this happens: a defensible analysis can be led down many paths, and unstated choices open a garden of forking paths (Simmons et al., 2011; Gelman and Loken, 2014), which laying the alternatives out as a multiverse makes visible (Steegen et al., 2016). Reporting standards in ecology have long argued that writing the choices down is what makes a study checkable (Parker et al., 2016; O'Dea et al., 2021; Zurell et al., 2020)."));
c.push(P("Artificial-intelligence coding tools introduce the same problem in a new place. An ecologist can now describe an analysis in ordinary words and receive a number, without writing any code. The models behind these tools do not respond identically to the same input, so the code and the answer can differ from one run to the next, and even the wording or layout of a request moves a model's behaviour (He et al., 2024; Yagubyan, 2026). Ecologists are beginning to use such tools for real work, from assistants that answer questions about a dataset (Gallois et al., 2025) to tests of how much ecological knowledge a general model holds (Dorm et al., 2026). What has not been measured is how often the resulting number is correct, and what makes it so."));
c.push(P("One response is to write the procedure down once, as a reusable specification that states which data to use, how to treat records that are absent, what quantity is wanted and by which method. Such a specification differs from a script in what it fixes. A script records how one dataset was handled and names its columns; a specification states what is to be computed and leaves the implementation to whoever runs it. Whether that difference matters in practice is an empirical question, and it is the question this paper addresses."));
c.push(P("Throughout we keep apart two properties that are easily confused (Goodman et al., 2016). The first is whether repeated runs of the same analysis return the same answer. The second is whether that answer matches an independently established correct value. An analysis can have either without the other, so we report them separately (Gundersen, 2021). We ask three questions. How often does an analysis described in ordinary words reach the correct value? Does a written specification change that, and does it do so more than supplying a working script? And what would a shared collection of such specifications have to check before accepting one?"));
c.push(PB());

// ---------------- 2 METHODS ----------------
c.push(H1("2  Materials and methods"));
c.push(H2("2.1  Tasks"));
c.push(P("We assembled twelve analysis tasks on four ecological datasets (Table 1). Each task states a question in the way an ecologist would ask a colleague, and each leaves one analytical choice open, so that more than one defensible number can be produced from the same file. The tasks were chosen to cover four kinds of open choice. The first is what counts as a sampling unit before values are averaged. The second is whether an estimate is pooled across groups or computed within them. The third is how records that are absent are treated, including rows that are missing from the file altogether because nothing was caught. The fourth is how a fitted model is set up, meaning the split of the data, the random seed and the scaling of predictors. Three tasks belong to each kind of choice, and no kind is confined to a single dataset, so that a result cannot be an artefact of one file."));
c.push(P("The datasets are the iris measurements, the Palmer Penguins measurements (Horst et al., 2020), twenty six years of rodent capture records from a long-term survey, and one year of reef-fish visual transect records from a marine monitoring programme. The first three are openly available and the fourth is available on request."));
c.push(TCAP("Table 1. The twelve tasks, the kind of choice each one leaves open, and the reference value. Every reference was computed by two independent implementations, which agreed to within numerical precision."));
c.push(table(
  ["Kind of open choice", "Task", "Dataset", "Reference"],
  [
    ["Sampling unit", "Mean per-transect fish biomass", "reef fish", "3.4642"],
    ["Sampling unit", "Mean rodents caught per plot and year", "rodents", "55.326"],
    ["Sampling unit", "Mean rodent species richness per plot and year", "rodents", "6.6882"],
    ["Scope of the estimate", "Correlation of sepal length and width", "iris", "−0.1176"],
    ["Scope of the estimate", "Correlation of bill length and depth", "penguins", "−0.2351"],
    ["Scope of the estimate", "Correlation of hindfoot length and weight", "rodents", "0.6838"],
    ["Missing records", "Mean body mass of female Gentoo penguins", "penguins", "4679.7"],
    ["Missing records", "Mean weight of one rodent species", "rodents", "43.158"],
    ["Missing records", "Mean rodents per plot and year counting empty plot-years", "rodents", "54.883"],
    ["Fitting a model", "Accuracy of a penguin sex classifier", "penguins", "0.8806"],
    ["Fitting a model", "Accuracy of an iris species classifier", "iris", "0.9333"],
    ["Fitting a model", "Accuracy of a rodent species classifier", "rodents", "0.8125"],
  ],
  [2100, 3400, 1500, 1400]
));

c.push(H2("2.2  Reference values"));
c.push(P("Each task carries a reference value, and the standing of that value matters, because a study of this kind is only as good as its notion of a correct answer. We therefore fixed the quantity to be estimated in words and then computed it twice, using two implementations written independently of one another, one built from the operations of a data-analysis library and one written as a direct loop over the records. A reference was accepted only where the two agreed to within numerical precision. Once the quantity is stated, the value follows from arithmetic rather than from our preference, and the two implementations guard against a mistake in either. The tolerance for judging a later answer correct was set in advance for each task and is given with the archived materials."));

c.push(H2("2.3  Three conditions"));
c.push(P("Every task was presented under three conditions. In the first the model received the question by itself. In the second it received the question together with a written specification, which states the data to use, the treatment of absent records, the quantity wanted and the method, in ordinary words and without any code. In the third it received the question together with a working script that answers a different question of the same kind on a different dataset, which it was told it could adapt. The third condition represents the established recommendation to share versioned code, and it is included so that the value of a written specification can be judged against it rather than against nothing."));
c.push(P("The script given in the third condition never solves the task in front of the model. Where a task was itself the source of a script, the script from another task of the same kind was supplied instead, so that no run received its own answer."));

c.push(H2("2.4  Models, runs and outcome"));
c.push(P("Each combination of task and condition was run ten times, five times on a model from each of two companies, giving 360 runs. The models were requested by the identifiers gpt-4.1 and gemini-pro-latest, and the sampling temperature was left at its default value of one, so that the variation reported here is the variation a user would meet. Every run went through the same procedure. The model was shown the question, the names of the columns and the first few rows of the file, as an analyst would see before starting, and returned a complete script. Every returned script was then executed in the same environment, and the number it printed was recorded. Showing the file in this way means the comparison is about the specification rather than about guessing what the columns are called."));
c.push(P("A run counts as correct when the number it returns falls within the stated tolerance of the reference. Because repeated runs of one task are repeated measures of that task and not independent observations, each task contributes a single figure to the analysis, namely the proportion of its runs that were correct under a given condition. Conditions were then compared across the twelve tasks with paired Wilcoxon signed-rank tests. The unit of replication is therefore the task, and the number of tasks, not the number of runs, sets the strength of the evidence."));

c.push(H2("2.5  Three further sets of runs"));
c.push(P("Three further sets of runs were carried out on a smaller collection of four tasks, three of which are also among the twelve. They are reported as description and not as evidence, because they use too few tasks for a task-level comparison, and no statistical test is applied to them and no conclusion of this paper rests on them. Their purpose is to show whether the behaviour seen in the twelve tasks survives three changes that an ecologist might expect to matter, namely the language the analysis is written in, the choice of model, and the difference between asking for a number and asking for a written account."));
c.push(P("The first set repeated each of the four tasks with the analysis written in R rather than in Python, with ten runs for each task and condition in each language. The second set repeated the reef-fish task on five models from three companies, with six runs for each model and condition. The third set replaced the request for a single number with a request for a short report on the penguin data answering four questions at once, with eight runs per condition, and recorded both the numbers the report contained and the conclusions it drew. In these three sets the instruction was given at several strengths, running from generic procedural steps, through a statement of the input and the method, to a full specification with a checklist of things to verify. The two ends of that range are the ones quoted below, and they correspond to the question alone and to the specification used in the main study."));
c.push(PB());

// ---------------- 3 RESULTS ----------------
c.push(H1("3  Results"));
c.push(H2("3.1  The twelve tasks"));
c.push(P("Given the question by itself, models reached the correct value in 57 per cent of runs when averaged across the twelve tasks. A written specification raised this to 90 per cent and a working script to 72 per cent. Across the twelve tasks the specification was better than the question alone (paired Wilcoxon P = 0.031) and also better than the script (P = 0.031), while the script was not distinguishable from the question alone (P = 0.109). The specification gave a higher proportion than the script on seven tasks, a lower proportion on one, and the same proportion on four."));
c.push(P("The average over all twelve tasks understates what happens where a choice is genuinely open, because seven of the tasks were already answered correctly in at least nine of ten runs without any instruction (Fig. 1). On those tasks the models settled on the same reading of the question that the specification later stated, so there was nothing left to correct. The remaining five tasks are the informative ones. On these the question by itself reached the correct value in 2 per cent of runs, the specification in 78 per cent and the script in 38 per cent. With five tasks a paired test cannot return a value below 0.0625, and that value was obtained for the specification against both other conditions, meaning every one of the five favoured the specification."));
c.push(img(path.join(S2, "fig1_trajectories.png"), 612, 348, "Each task under each of the three conditions"));
c.push(CAP("Figure 1. Each line follows one task across the three conditions, which is how the tasks were compared, since the comparison is made within a task and not between tasks. The vertical position is the proportion of that task's ten runs that reached the reference value. The seven tasks drawn in grey were already answered correctly without any instruction and stay near the top throughout. The five drawn in blue are those where the question left a choice genuinely open, and all five rise from the question alone to the specification. The thick orange line is the mean of all twelve tasks. Colours are safe for colour vision deficiency."));

c.push(P("The kind of open choice determined how much the instruction mattered. Where the question concerned the scope of an estimate the models were already correct without help, reaching 97 per cent given the question alone, because the pooled reading that the specification asked for is also the one they adopted unprompted. Where a model had to be fitted the models were almost never correct without help, reaching 3 per cent, because the split of the data, the random seed and the scaling were left free and each run chose differently. Tasks about the sampling unit and about missing records fell between these, at 67 and 63 per cent."));
c.push(P("On several tasks the runs did not scatter. Asked for the mean number of rodents caught in a plot in a year, all five runs that produced a number without a specification returned 55.326, when the value that counts plot-years with no captures as the zeros they are is 54.883. Asked for the accuracy of an iris classifier, six of nine runs returned 0.9667 against a reference of 0.9333. In these cases the runs agreed with one another while being wrong, so neither repeating the analysis nor comparing two runs would have revealed the error (Fig. 2). The reef-fish task behaved in the same way, with runs settling on a value that follows from treating each combination of reef, habitat and transect as a survey unit rather than each combination of reef and transect."));
c.push(img(path.join(S2, "fig2_consensus.png"), 648, 216, "The values the runs actually returned"));
c.push(CAP("Figure 2. The numbers returned by individual runs on the three tasks where the runs given the question alone agreed most strongly on a value that is not the reference. The upper row of each panel is the question alone and the lower row is the question with a specification. The dashed green line is the reference value and each panel keeps its own scale, because the errors of interest are a few per cent from the reference and a shared scale would hide them. Points that fall on top of one another are runs that returned the same number, so the annotation gives how many runs agreed and on what. Runs that returned a number far outside the plotted range are counted in the corner rather than drawn, since including them would compress the rest of the panel to a point."));

c.push(P("The pattern held for both companies' models. Given the question alone the two reached 57 and 58 per cent, and with a specification they reached 100 and 80 per cent. The advantage of the specification over the script was present for both, at 100 against 67 per cent for one and 80 against 77 per cent for the other."));
c.push(P("A further set of runs asked how far a specification carries when the same data are presented differently. Repeating one task on the same records after renaming every column and changing the code used for a missing value, the specification reached the reference in 92 per cent of runs and the script in 75 per cent. Rearranging the same records into a long format, with one row per measurement rather than one row per observation, defeated both, and neither reached the reference in any run. A specification therefore survives a change in what the columns are called but not a change in how the table is organised."));

c.push(H2("3.2  Language, choice of model, and asking for a report"));
c.push(P("Writing the analysis in another language did not change the answer. On the reef-fish task every one of the ten runs written in Python without a specification returned 3.29521, and every one of the ten runs written in R without a specification returned the same value to six decimal places, when the reference is 3.46419. Once the sampling unit and the aggregation were stated, both languages returned the reference. On the correlation task, and on a further task asking for the proportion of variance in body mass accounted for by species, the two languages agreed with each other to eight decimal places in every condition. The task that fits a classifier behaved differently. A full specification made the runs within each language identical, but the two languages then settled on different numbers, 0.8806 in Python and 0.8657 in R, because the fitting procedure supplied by each language's standard library is not the same procedure. A specification stated at the level of the method therefore brings runs into agreement within a language, and brings two languages into agreement where the quantity is a matter of arithmetic, but not where the estimator itself differs between them."));
c.push(P("Moving to another model would not have exposed the error either. The reef-fish task was run six times on each of five models from three companies. Given the question alone, two of the five returned 3.2952 in every run, two returned 33.776 in every run, and one returned the reference in every run. The two wrong values differ from one another by an order of magnitude, so these models were not disagreeing about precision but computing different quantities, and each held to its own quantity across all six of its runs. A researcher comparing two models could therefore have found agreement, disagreement, or agreement on a wrong number, according to which two were compared. With the full specification, four of the five models returned the reference in every run and the fifth in four of its six runs."));
c.push(P("Asking for a written report rather than a single number showed the same pattern together with one observation that the single-number tasks cannot show. Eight runs were asked for a short report on the penguin data answering four questions at once. Given the question alone, the numbers in the report matched the reference for three of the four questions and never for the fourth, which was the question requiring a classifier to be fitted, and the reports followed the method they themselves declared in 79 per cent of the items checked. With a full specification all four numbers matched the reference and every declared item was followed. The conclusions the reports drew were nevertheless the same in every run and in every condition. Each named the same species as the heaviest, reported that body mass differs between species, reported that sex can be predicted from body measurements, and reported that flipper length increases with body mass. The written account of the analysis was therefore stable while the numbers underneath it were not, so a reader comparing two reports would have seen nothing to suggest that anything had differed."));
c.push(PB());

// ---------------- 4 WHAT A SPECIFICATION NEEDS ----------------
c.push(H1("4  What a specification needs to contain"));
c.push(P("Two requirements follow from the results. The first is to fix the settings that govern any randomness whenever a model is fitted, meaning the split of the data, the seed and the scaling of predictors, since this is where the question alone almost never produced the correct value. The second is to fix the input and the method whenever the sampling unit, the treatment of absent records, the scope of the estimate or the choice of statistic could change the quantity being estimated. Which of the two matters depends on the task, and a specification that fixes neither adds nothing."));
c.push(P("A specification also has to state what is returned and how close an answer must be to count as the same, because agreement between runs and agreement with a reference are different properties and a set of runs can have the first without the second. This does not mean that every choice should be frozen. A specification should say which choices define the intended quantity and must be fixed, which may vary, and how any variation that is allowed is to be judged."));
c.push(P("The results also mark the limit of what a specification does. Because it names the quantity rather than the implementation, it survives a change in the names of the columns, which a script does not. Because it still assumes a particular shape of table, it does not survive a rearrangement of the file. There is a third boundary, visible in the runs written in two languages. A specification fixes the quantity but not the estimator, so where the standard libraries of two languages fit a model by different procedures, both can follow the specification exactly and still return different numbers. A collection of specifications meant for shared use would therefore need to record the shape of data each one assumes and the language it was written against, and to treat a change in either as calling for a new specification rather than as something the reader will absorb."));
c.push(H2("4.1  Three checks for a shared collection"));
c.push(P("The measures used here become three checks that a shared collection of specifications could apply before accepting one. A repetition check runs the specification several times on fixed data and confirms that the answers agree within the stated tolerance. A reference check compares the answer with a value produced independently. A method check has a separate reader confirm that the analysis followed the method the specification declares. No one of the three stands in for another, since the tasks reported here include cases where runs agreed with one another while none of them matched the reference. A collection that applied only the first check would have accepted those cases."));
c.push(PB());

// ---------------- 5 DISCUSSION ----------------
c.push(H1("5  Discussion"));
c.push(H2("5.1  Why writing the method down did more than sharing the code"));
c.push(P("The comparison with a working script is the part of this study with the most direct bearing on practice, because sharing versioned code is the established recommendation for making an analysis repeatable. A script carries a complete answer for the dataset it was written against, including the names of its columns and the shape of its table. When the question moves to another dataset of the same kind, those particulars have to be undone before the method underneath can be reused, and the runs given a script frequently reproduced the earlier dataset's handling rather than the current dataset's requirement. A specification carries the method without the particulars, so there is less to undo. This is why the same information delivered as prose was more use than the same information delivered as code, and it suggests that the two are complements rather than substitutes."));
c.push(H2("5.2  Agreement between runs is not evidence of correctness"));
c.push(P("The most consequential finding for anyone using these tools is that the errors were not noisy. On three of the five informative tasks the runs converged on a single wrong number, and on one of them every run that produced a value returned the same wrong number. The two checks an ecologist would naturally apply, which are to run the analysis again and to try a different model, would have returned the same answer and increased confidence in it. The wrong values were not absurd either. Counting only the plot-years that appear in a file, rather than the plot-years that were surveyed, gives a mean that is a little too high and entirely plausible. Treating each combination of reef, habitat and transect as a survey unit gives a biomass a few per cent below the value the monitoring programme reports. An error of this size passes review, and it is the kind of error that a specification of the sampling unit prevents."));
c.push(P("The further sets of runs show that the two remaining checks an ecologist might apply would also have passed. Rewriting the analysis in another language returned the same wrong value on the reef-fish task, so a colleague working in R would have confirmed the Python result. Running the task on five models from three companies returned wrong values from four of them, held consistently within each model, so a comparison between models could as easily have produced agreement on an error as disagreement. Asking for a written report rather than a number showed the sharpest form of the problem, because the conclusions the reports drew were identical in every condition while the numbers behind them were not. The part of an analysis that a reader sees was the part that did not vary."));
c.push(H2("5.3  Where an instruction was unnecessary"));
c.push(P("Seven of the twelve tasks were answered correctly without any instruction, and this deserves as much emphasis as the tasks where instruction mattered. Where a question has one reading that a competent analyst would adopt, current models adopt it, and a specification adds nothing except a record of what was intended. The effort of writing one is repaid where a question has more than one defensible reading, and the four kinds of open choice used here are a workable guide to finding those cases. The practical advice that follows is not to specify everything, but to run an analysis without a specification first, see where repeated runs disagree or where the value differs from an independent calculation, and write the specification against what is found."));
c.push(H2("5.4  Limitations"));
c.push(P("Twelve tasks on four datasets is a small sample of ecological analysis, and although each kind of open choice is represented by three tasks the estimate for each kind rests on those three. Models from two companies were used in the twelve-task study and from three in the further sets of runs, and behaviour may differ elsewhere. Those further sets rest on four tasks, which is too few to compare conditions in the way the twelve allow, so they are reported as description and carry no test, and the conclusions of this paper would stand without them. The reference values are correct given the quantity each task states, but the choice of quantity is ours, and for a question such as the definition of a survey unit an ecologist could state a different quantity and be right to do so; what the results show is that the value returned without a specification did not match the quantity the question intended, not that one convention is universally correct. The runs that show agreement on a wrong value come from tasks where such agreement is possible, so the frequency of that behaviour across ecological analysis as a whole is not estimated here. The tolerance for each task was fixed before the runs but was chosen by us. Finally, the tasks were single steps rather than multi-step analyses in which one choice feeds the next, and the behaviour of longer workflows was not examined."));
c.push(H2("5.5  Further work"));
c.push(P("The clearest extension is to multi-step analyses, where the number of open choices grows and where an error in an early step is carried forward. A second is to widen the range of models, including smaller models that a research group might run locally. A third is to test whether specifications written by one group are used correctly by another, which is the property a shared collection depends on and which the present design does not measure. The materials here, including the tasks, the reference values and the procedure for running them, are arranged so that further tasks can be added to the same frame."));

// ---------------- 6 CONCLUSIONS ----------------
c.push(H1("6  Conclusions"));
c.push(P("An analysis described to an artificial-intelligence tool in ordinary words reached the correct value in a little over half of runs, and in one run in fifty where the question left a real choice open. Writing the method down as a specification raised this to nine runs in ten, and did so more effectively than supplying a working script, because a specification states the quantity while a script records the handling of one dataset. On several tasks the runs agreed with one another while being wrong, so neither repetition nor a second model would have exposed the error, which means agreement and correctness have to be established separately. Rewriting the analysis in another language returned the same wrong number, and when the request was for a written report rather than a number, the conclusions the report drew were the same whether or not the numbers behind them were right. Where a question has only one sensible reading a specification adds nothing, and the effort belongs where more than one reading is defensible."));

// ---------------- REFERENCES ----------------
c.push(H1("References"));
const refs = [
  "Baker, M. (2016). 1,500 scientists lift the lid on reproducibility. Nature, 533, 452–454.",
  "Botvinik-Nezer, R., Holzmeister, F., Camerer, C. F., et al. (2020). Variability in the analysis of a single neuroimaging dataset by many teams. Nature, 582, 84–88. https://doi.org/10.1038/s41586-020-2314-9",
  "Breznau, N., Rinke, E. M., Wuttke, A., et al. (2022). Observing many researchers using the same data and hypothesis reveals a hidden universe of uncertainty. Proceedings of the National Academy of Sciences, 119(44), e2203150119. https://doi.org/10.1073/pnas.2203150119",
  "Cooper, N., & the BES Data and Code Hackathon Group. (2026). Data- and code-archiving in the British Ecological Society journals: Present status and recommendations for future improvements. Methods in Ecology and Evolution. https://doi.org/10.1111/2041-210X.70338",
  "Culina, A., van den Berg, I., Evans, S., & Sánchez-Tójar, A. (2020). Low availability of code in ecology: a call for urgent action. PLOS Biology, 18(7), e3000763.",
  "Dorm, F., Millard, J., Purves, D., Harfoot, M., & Mac Aodha, O. (2026). Large language models possess some ecological knowledge, but how much? Ecological Informatics, 103699.",
  "Gallois, E. C., Salili-James, A., Poon, S. T. S., Trebski, A., & Redding, D. W. (2025). Fast-tracking ecological interpretation using bespoke quantitative large language models. Methods in Ecology and Evolution, 16, 2730–2740.",
  "Gelman, A., & Loken, E. (2014). The statistical crisis in science. American Scientist, 102(6), 460. https://doi.org/10.1511/2014.111.460",
  "Goodman, S. N., Fanelli, D., & Ioannidis, J. P. A. (2016). What does research reproducibility mean? Science Translational Medicine, 8(341), 341ps12.",
  "Gould, E., Fraser, H. S., Parker, T. H., Nakagawa, S., et al. (2025). Same data, different analysts: variation in effect sizes due to analytical decisions in ecology and evolutionary biology. BMC Biology, 23, 35. https://doi.org/10.1186/s12915-024-02101-x",
  "Gundersen, O. E. (2021). The fundamental principles of reproducibility. Philosophical Transactions of the Royal Society A, 379, 20200210.",
  "He, J., Rungta, M., Koleczek, D., Sekhon, A., Wang, F. X., & Hasan, S. (2024). Does prompt formatting have any impact on LLM performance? arXiv:2411.10541.",
  "Horst, A. M., Hill, A. P., & Gorman, K. B. (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data. R package; data from Gorman, Williams & Fraser (2014), PLOS ONE 9(3), e90081.",
  "Kambouris, S., Wilkinson, D. P., Smith, E. T., & Fidler, F. (2024). Computationally reproducing results from meta-analyses in ecology and evolutionary biology using shared code and data. PLOS ONE, 19(3), e0300333.",
  "O'Dea, R. E., Lagisz, M., Jennions, M. D., et al. (2021). Preferred reporting items for systematic reviews and meta-analyses in ecology and evolutionary biology: a PRISMA extension (PRISMA-EcoEvo). Biological Reviews, 96, 1695–1722.",
  "Parker, T. H., Forstmeier, W., Koricheva, J., et al. (2016). Transparency in ecology and evolution: real problems, real solutions. Trends in Ecology & Evolution, 31(9), 711–719. https://doi.org/10.1016/j.tree.2016.07.002",
  "Silberzahn, R., Uhlmann, E. L., Martin, D. P., et al. (2018). Many analysts, one data set: making transparent how variations in analytic choices affect results. Advances in Methods and Practices in Psychological Science, 1(3), 337–356. https://doi.org/10.1177/2515245917747646",
  "Simmons, J. P., Nelson, L. D., & Simonsohn, U. (2011). False-positive psychology: undisclosed flexibility in data collection and analysis allows presenting anything as significant. Psychological Science, 22(11), 1359–1366. https://doi.org/10.1177/0956797611417632",
  "Steegen, S., Tuerlinckx, F., Gelman, A., & Vanpaemel, W. (2016). Increasing transparency through a multiverse analysis. Perspectives on Psychological Science, 11(5), 702–712. https://doi.org/10.1177/1745691616658637",
  "Yagubyan, A. (2026). How consistent are LLM agents? Measuring behavioral reproducibility in multi-step tool-calling pipelines. arXiv:2605.28840.",
  "Zurell, D., Franklin, J., König, C., et al. (2020). A standard protocol for reporting species distribution models (ODMAP). Ecography, 43(9), 1261–1277.",
];
refs.forEach(r => c.push(REFP(r)));

const doc = buildDoc(c, { title: "Specifications and AI data analysis in ecology", footerLeft: "Specifications and AI data analysis in ecology" });
write(doc, path.join(__dirname, "Manuscript_Specifications_AI_Ecology.docx"));
