const T = require("./theme.js");
const { P, TITLE, H1, H2, CAP, TCAP, NUM, REFP, PB, img, table, buildDoc, write } = T;
const path = require("path");
const S2 = path.resolve(__dirname, "..", "main_study");

const c = [];

// ---------------- TITLE / ABSTRACT ----------------
c.push(TITLE("Repeated AI analyses of ecological data agree on wrong answers until the method is written down"));
c.push(P("Article type: Research Article. Target journal: Methods in Ecology and Evolution.", { size: 20, spacing: { after: 20 } }));
c.push(P("This manuscript is prepared for double-anonymous review. Author names, affiliations, the running headline, and all statements are on the separate title page.", { size: 20 }));

c.push(H1("Abstract"));
c.push(P("1. Ecologists increasingly describe a data analysis to an artificial-intelligence tool in ordinary words. The same request can return a different answer each time, and nothing in the answer shows whether it is right. We asked how often such an analysis reaches the correct value, and whether writing the method down as a reusable specification does more for it than supplying a working script."));
c.push(P("2. We assembled twelve analysis tasks on four ecological datasets, three for each of four kinds of open analytical choice, from what counts as a sampling unit to how a fitted model is set up. Each poses a question as an ecologist would ask it and has a reference value on which two independent implementations agree. Every task was run under three conditions, the question by itself, the question with a written specification, and the question with a working script for a related task, ten runs each across models from two companies, with the task as the unit of replication."));
c.push(P("3. Given the question by itself, models reached the correct value in 59 per cent of runs across all tasks, and in 3 per cent of runs on the five tasks where a choice was genuinely open. A written specification raised these figures to 96 and 90 per cent, and a working script to 75 and 44 per cent. Agreement between runs tracked correctness poorly, since the script made runs agree with one another as often as the specification did, and on one task all ten runs given a script returned the same wrong number, so repeating the analysis, rewriting it in a second language or moving to another company's model would each have confirmed the error."));
c.push(P("4. Writing the method down changed the answer more than sharing code did, because a specification states what is to be computed while a script records how one dataset was handled. Agreement between runs was not evidence of correctness, so the two have to be checked separately. We set out what a specification needs to contain and three checks a shared collection should apply."));
c.push(P("Data and code for peer review: the tasks, reference values, prompts, run records, analysis scripts and figures are available in an anonymised repository at https://anonymous.4open.science/r/ai-skills-reproducibility-ecology-B13E/README.md.", { spacing: { before: 120 } }));
c.push(P("Keywords: analytical choices; artificial intelligence; large language models; open science; reproducibility; research software; specification; workflow provenance.", { spacing: { before: 120 } }));
c.push(PB());

// ---------------- 1 INTRODUCTION ----------------
c.push(H1("1  Introduction"));
c.push(P("Science rests on results that other people can obtain again, yet a computed result is often hard to regenerate. More than seven in ten of the researchers in one survey had failed to reproduce another group's result (Baker, 2016). Ecology shows the same pattern, and the difficulty lies mostly in the analysis rather than in the data. Fewer than a fifth of the ecology papers examined by Culina et al. (2020) could be reproduced from the code that accompanied them, and a survey of the journals of the British Ecological Society found that almost every paper shared its data while only about a third shared its code (Cooper and the BES Data and Code Hackathon Group, 2026). Even where both were available, one team reproduced the published result in between a quarter and three quarters of cases, depending on how strictly a match was judged (Kambouris et al., 2024)."));
c.push(P("Part of the difficulty has nothing to do with software. When several teams are given the same data and the same question, they reach different answers, because each makes reasonable but different analytical choices along the way (Silberzahn et al., 2018; Botvinik-Nezer et al., 2020; Breznau et al., 2022). The same spread has now been shown for ecological and evolutionary data (Gould et al., 2025). Work on analytical flexibility describes why this happens: a defensible analysis can be led down many paths, and unstated choices open a garden of forking paths (Simmons et al., 2011; Gelman and Loken, 2014), which laying the alternatives out as a multiverse makes visible (Steegen et al., 2016). Reporting standards in ecology have long argued that writing the choices down is what makes a study checkable (Parker et al., 2016; O'Dea et al., 2021; Zurell et al., 2020)."));
c.push(P("Artificial-intelligence coding tools introduce the same problem in a new place. An ecologist can now describe an analysis in ordinary words and receive a number, without writing any code. The models behind these tools do not respond identically to the same input, and when asked to write code they return different programs for the same request often enough that this has been measured directly (Ouyang et al., 2023), while the wording or layout of a request also moves a model's behaviour (He et al., 2024; Yagubyan, 2026). Ecologists are beginning to use such tools for real work, from assistants that answer questions about a dataset (Gallois et al., 2025) to tests of how much ecological knowledge a general model holds (Dorm et al., 2026). What has not been measured is how often the resulting number is correct, and what makes it so."));
c.push(P("One response is to write the procedure down once, as a reusable specification that states which data to use, how to treat records that are absent, what quantity is wanted and by which method. Such a specification differs from a script in what it fixes. A script records how one dataset was handled and names its columns; a specification states what is to be computed and leaves the implementation to whoever runs it. Whether that difference matters in practice is an empirical question, and it is the question this paper addresses."));
c.push(P("Throughout we keep apart two properties that are easily confused (Goodman et al., 2016). The first is whether repeated runs of the same analysis return the same answer. The second is whether that answer matches an independently established correct value. An analysis can have either without the other, so we report them separately (Gundersen, 2021). We therefore ask three questions, of which the first is how often an analysis described in ordinary words reaches the correct value. The second is whether a written specification changes that, and whether it does so more than supplying a working script. The third is what a shared collection of such specifications would have to check before accepting one."));
c.push(PB());

// ---------------- 2 METHODS ----------------
c.push(H1("2  Materials and methods"));
c.push(H2("2.1  Tasks"));
c.push(P("We assembled twelve analysis tasks on four ecological datasets (Table 1). Each task states a question in the way an ecologist would ask a colleague, and each leaves one analytical choice open, so that more than one defensible number can be produced from the same file. The tasks were chosen to cover four kinds of open choice. The first is what counts as a sampling unit before values are averaged. The second is whether an estimate is pooled across groups or computed within them. The third is how records that are absent are treated, including rows that are missing from the file altogether because nothing was caught. The fourth is how a fitted model is set up, meaning the split of the data, the random seed and the scaling of predictors. Three tasks belong to each kind of choice, and no kind is confined to a single dataset, so that a result cannot be an artefact of one file."));
c.push(P("The datasets are the iris measurements, the Palmer Penguins measurements (Horst et al., 2020), twenty six years of rodent capture records from a long-term survey, and one year of reef-fish visual transect records from a marine monitoring programme. The first three are openly available and the fourth is available on request."));
c.push(TCAP("Table 1. The twelve tasks, the kind of choice each one leaves open, and the reference value. Every reference was computed by two independent implementations, which agreed to within numerical precision."));
c.push(table(
  ["Kind of open choice", "Task", "Dataset", "Reference"],
  [
    ["Sampling unit", "Mean per-transect fish biomass", "reef fish", "3.4642"],
    ["Sampling unit", "Mean rodents caught per plot and year", "rodents", "55.326"],
    ["Sampling unit", "Mean rodent species richness per plot and year", "rodents", "6.6882"],
    ["Scope of the estimate", "Correlation of sepal length and width", "iris", "−0.1176"],
    ["Scope of the estimate", "Correlation of bill length and depth", "penguins", "−0.2351"],
    ["Scope of the estimate", "Correlation of hindfoot length and weight", "rodents", "0.6838"],
    ["Missing records", "Mean body mass of female Gentoo penguins", "penguins", "4679.7"],
    ["Missing records", "Mean weight of one rodent species", "rodents", "43.158"],
    ["Missing records", "Mean rodents per plot and year counting empty plot-years", "rodents", "54.883"],
    ["Fitting a model", "Accuracy of a penguin sex classifier", "penguins", "0.8806"],
    ["Fitting a model", "Accuracy of an iris species classifier", "iris", "0.9333"],
    ["Fitting a model", "Accuracy of a rodent species classifier", "rodents", "0.8125"],
  ],
  [2100, 3400, 1500, 1400]
));

c.push(H2("2.2  Reference values"));
c.push(P("Each task carries a reference value, and the standing of that value matters, because a study of this kind is only as good as its notion of a correct answer. We therefore fixed the quantity to be estimated in words and then computed it twice, using two implementations written independently of one another, one built from the operations of a data-analysis library and one written as a direct loop over the records. A reference was accepted only where the two agreed to within numerical precision. Once the quantity is stated, the value follows from arithmetic rather than from our preference, and the two implementations guard against a mistake in either. The tolerance for judging a later answer correct was set in advance for each task and is given with the archived materials."));

c.push(H2("2.3  Three conditions"));
c.push(P("Every task was presented under three conditions, of which the first gave the model the question by itself. In the second it received the question together with a written specification, which states the data to use, the treatment of absent records, the quantity wanted and the method, in ordinary words and without any code. In the third it received the question together with a working script that answers a different question of the same kind on a different dataset, which it was told it could adapt. The third condition represents the established recommendation to share versioned code, and it is included so that the value of a written specification can be judged against it rather than against nothing."));
c.push(P("The script given in the third condition never solves the task in front of the model. Where a task was itself the source of a script, the script from another task of the same kind was supplied instead, so that no run received its own answer."));

c.push(H2("2.4  Models, runs and outcome"));
c.push(P("Each combination of task and condition was run ten times, five times on a model from each of two companies, giving 360 runs. The models were requested by the identifiers gpt-4.1 and gemini-pro-latest, and the sampling temperature was left at its default value of one, so that the variation reported here is the variation a user would meet. Every run then went through the same procedure, in which the model was shown the question, the names of the columns and the first few rows of the file, as an analyst would see before starting, and returned a complete script. Every returned script was then executed in the same environment, and the number it printed was recorded. Showing the file in this way means the comparison is about the specification rather than about guessing what the columns are called."));
c.push(P("A run counts as correct when the number it returns falls within the stated tolerance of the reference. Because repeated runs of one task are repeated measures of that task and not independent observations, each task contributes a single figure to the analysis, namely the proportion of its runs that were correct under a given condition. Conditions were then compared across the twelve tasks with paired Wilcoxon signed-rank tests, and the paired difference is also reported with a confidence interval obtained by resampling tasks. The unit of replication is therefore the task, and the number of tasks, not the number of runs, sets the strength of the evidence."));
c.push(P("Runs can fail to produce a number for two unrelated reasons, and the two are treated differently. A model may return a script that does not run or prints nothing that can be read, which is a property of the condition and counts as an incorrect answer, since an analysis that does not run has not given the user the right number. A call may also fail because of a network or quota error at the provider, which has nothing to do with the condition. Twenty seven of the 360 calls failed in this second way, spread across conditions at 14, 6 and 7 runs of 120, which is not distinguishable from an even spread (chi-square = 4.56, two degrees of freedom, P = 0.102). All twenty seven were calls to one of the two companies, so excluding them removes runs from one model and not from the other, and three of the thirty six combinations of task and condition are left resting on a single model. The analysis reported below excludes these calls and keeps every other failure as incorrect. Because this choice affects one of the comparisons, results under the two alternatives, namely counting every run and counting only the runs that returned a number, are reported alongside and in full in the Supporting Information."));
c.push(P("Whether runs agree with one another was measured separately from whether they are right, since the argument of this paper is that these are different properties. For each task and condition we take the runs that returned a number, group values that fall within the task's own tolerance of each other, and record the size of the largest group and whether the value that group agrees on is the reference. Agreement therefore means close enough to count as the same answer, rather than identical to an arbitrary number of decimal places."));

c.push(H2("2.5  Three further sets of runs"));
c.push(P("Three further sets of runs were carried out on a smaller collection of four tasks, three of which are also among the twelve. They are reported as description and not as evidence, because they use too few tasks for a task-level comparison, and no statistical test is applied to them and no conclusion of this paper rests on them. Their purpose is to show whether the behaviour seen in the twelve tasks survives three changes that an ecologist might expect to matter, namely the language the analysis is written in, the choice of model, and the difference between asking for a number and asking for a written account."));
c.push(P("The first set repeated each of the four tasks with the analysis written in R rather than in Python, with ten runs for each task and condition in each language. The second set repeated the reef-fish task on five models from three companies, with six runs for each model and condition. The third set replaced the request for a single number with a request for a short report on the penguin data answering four questions at once, with eight runs per condition, and recorded both the numbers the report contained and the conclusions it drew. In these three sets the instruction was given at several strengths, running from generic procedural steps, through a statement of the input and the method, to a full specification with a checklist of things to verify. The two ends of that range are the ones quoted below, and they correspond to the question alone and to the specification used in the main study."));
c.push(PB());

// ---------------- 3 RESULTS ----------------
c.push(H1("3  Results"));
c.push(H2("3.1  How often each condition reached the correct value"));
c.push(P("Given the question by itself, models reached the correct value in 59 per cent of runs when averaged across the twelve tasks. A written specification raised this to 96 per cent and a working script to 75 per cent. Across the twelve tasks the specification was ahead of the question alone by 37 percentage points (95 per cent confidence interval 13 to 62, paired Wilcoxon P = 0.031), and ahead of the script by 21 points (7 to 37, P = 0.031). The script was ahead of the question alone by 16 points (1 to 34), and the paired test did not support that difference (P = 0.094). The specification reached a higher proportion than the script on six tasks and a lower proportion on none, with the remaining six tied. Results for every task and condition separately are given in Supporting Information Table S2."));
c.push(P("Seven of the twelve tasks were answered correctly in at least nine of ten runs without any instruction (Fig. 1). On the remaining five the question by itself reached the correct value in 3 per cent of runs, the specification in 90 per cent and the script in 44 per cent. With five tasks a paired test cannot return a value below 0.0625, and that value was obtained for the specification against both other conditions, so every one of the five favoured the specification."));
c.push(P("The comparison between the specification and the script depends on how failed runs are counted. The specification is ahead of the script whether every run is counted (90 against 72 per cent, P = 0.031) or calls that failed at the provider are excluded, as above. Among only those runs that returned a number at all the two are not distinguishable (96 against 85 per cent, P = 0.500). Ten of the runs given a script returned code that did not run or printed nothing that could be read, against none of the runs given a specification, and five of those ten were on a single task."));
c.push(img(path.join(S2, "fig1_trajectories.png"), 612, 348, "Each task under each of the three conditions"));
c.push(CAP("Figure 1. Each line follows one task across the three conditions, which is how the tasks were compared, since the comparison is made within a task and not between tasks. The vertical position is the proportion of that task's runs that reached the reference value, out of the ten attempted less any calls that failed at the provider. The seven tasks drawn in grey were already answered correctly without any instruction and stay near the top throughout. The five drawn in blue are those where the question left a choice genuinely open, and all five rise from the question alone to the specification. The thick orange line is the mean of all twelve tasks. Colours are safe for colour vision deficiency."));

c.push(P("Accuracy without an instruction differed by the kind of open choice, at 67 per cent for the sampling unit, 97 per cent for the scope of an estimate, 67 per cent for missing records and 6 per cent where a model had to be fitted. With a specification the same four kinds reached 100, 100, 83 and 100 per cent, and with a script 73, 93, 67 and 67 per cent."));

c.push(H2("3.2  Agreement between runs, measured separately from correctness"));
c.push(P("Counting a task as showing agreement when at least four fifths of the runs that returned a number fell within its tolerance of one value, the question alone produced agreement on eight of the twelve tasks, the script on eleven and the specification on eleven. The value agreed on was not the reference on one of those tasks under the question alone, on one under the script, and on none under the specification."));
c.push(P("On the task that asks for the mean number of rodents caught in a plot in a year, counting the plot-years in which nothing was caught, the reference is 54.883. Every one of the ten runs given a working script returned 55.326, which is the reference value of another task in this study, the one that asks for the mean catch per plot and year without the instruction about empty plot-years (Table 1), matched to seven decimal places, with several runs returning it digit for digit and the rest differing only in how many digits they printed. Given the question alone, all five runs that returned a number returned that same value, and those five came from one of the two models, the calls to the other model on that combination of task and condition having failed at the provider. With a specification, five of the ten runs reached the reference."));
c.push(P("Two further tasks show the same pattern. Six of nine runs given the question alone returned 0.9667 for the accuracy of an iris classifier, against a reference of 0.9333, and on the reef-fish task three of six runs returned 3.295 against a reference of 3.464. On the penguin sex model the runs given the question alone returned nine different values in ten runs (Fig. 2)."));
c.push(img(path.join(S2, "fig2_consensus.png"), 648, 376, "What the runs actually returned"));
c.push(CAP("Figure 2. The numbers returned by individual runs, for the five tasks where the question alone did not reach the reference. Each panel shows all three conditions. The dashed green line is the reference value. Counts give how many of the runs that returned a number agreed on one value, within that task's tolerance, and are printed in green where the agreed value is the reference. Each panel keeps its own scale, since the errors of interest are a few per cent from the reference. Runs that returned a number far outside the plotted range are counted in the corner rather than drawn, because including them would compress the rest of the panel to a point."));

c.push(H2("3.3  Both companies' models, and a change in how the data are presented"));
c.push(P("Both companies' models showed the same ordering from different starting points. Given the question alone one reached 57 per cent and the other 73 per cent, and with a specification they reached 100 and 91 per cent. Against the script the figures were 100 against 67 per cent for the first and 91 against 85 per cent for the second."));
c.push(P("A further set of runs, on one task and reported without a test, asked how far a specification carries when the same data are presented differently. After renaming every column and changing the code used for a missing value, the specification reached the reference in 92 per cent of runs and the script in 75 per cent. After rearranging the same records into a long format, with one row per measurement rather than one row per observation, neither reached the reference in any run."));

c.push(H2("3.4  Language, choice of model, and asking for a report"));
c.push(P("On the reef-fish task every one of the ten runs written in Python without a specification returned 3.29521, and every one of the ten runs written in R without a specification returned the same value to six decimal places, against a reference of 3.46419. Once the sampling unit and the aggregation were stated, both languages returned the reference. On the correlation task, and on a further task asking for the proportion of variance in body mass accounted for by species, the two languages agreed with each other to eight decimal places in every condition. On the task that fits a classifier, a full specification made the runs within each language identical, and the two languages then returned different values, 0.8806 in Python and 0.8657 in R."));
c.push(P("The reef-fish task was also run six times on each of five models from three companies. Given the question alone, two of the five returned 3.2952 in every run, two returned 33.776 in every run, and one returned the reference in every run. With the full specification, four of the five returned the reference in every run and the fifth in four of its six runs."));
c.push(P("Eight runs per condition were asked for a short report on the penguin data answering four questions at once, rather than for a single number. Given the question alone, the numbers in the report matched the reference for three of the four questions and never for the fourth, which was the question requiring a classifier to be fitted, and the reports followed the method they themselves declared in 79 per cent of the items checked. With a full specification all four numbers matched the reference and every declared item was followed. The conclusions the reports stated were the same in every run and in every condition, each naming the same species as the heaviest and reporting that body mass differs between species, that sex can be predicted from body measurements, and that flipper length increases with body mass."));
c.push(PB());

// ---------------- 4 DISCUSSION ----------------
c.push(H1("4  Discussion"));
c.push(H2("4.1  Why writing the method down did more than sharing the code"));
c.push(P("The comparison with a working script is the part of this study with the most direct bearing on practice, because sharing versioned code in a fixed environment is the established recommendation for making an analysis repeatable (Sandve et al., 2013), and ecology has spent a decade arguing that code deserves the same standing as data (Mislan et al., 2016; Culina et al., 2020; Cooper and the BES Data and Code Hackathon Group, 2026). Nothing here argues against that, and what the results show is that code delivers reproducibility more readily than it delivers the right answer, which is consistent with the finding that published code often fails to regenerate the published result even when it is available and runs (Kambouris et al., 2024). A script carries a complete answer for the dataset it was written against, including the names of its columns and the shape of its table. When the question moves to another dataset of the same kind, those particulars have to be undone before the method underneath can be reused, and the runs given a script frequently reproduced the earlier dataset's handling rather than the current dataset's requirement. A specification carries the method without the particulars, so there is less to undo."));
c.push(P("The advantage of the specification over the script has two parts, and they should be kept separate because the evidence for them differs. The first is that the specification produced code that ran. Ten runs given a script returned something that could not be executed or read, against none given a specification, and an analysis that does not run has not answered the question. The second is that among runs which did return a number the specification was still ahead, by 96 per cent against 85, although with twelve tasks that difference is not supported by a paired test. The practical advice therefore rests more firmly on the first part than on the second, and a larger set of tasks would be needed to settle the second."));
c.push(P("Ecology has met a version of this problem before and answered it in the same way. Simulation modellers found that releasing code did not allow others to understand or rebuild a model, and adopted a written protocol that states the design, the entities and the assumptions in ordinary prose, with the code supplied separately (Grimm et al., 2020). The same reasoning produced a reporting protocol for species distribution models (Zurell et al., 2020) and one for evidence synthesis in ecology and evolution (O'Dea et al., 2021), and it underlies the broader argument that transparency about analytical choices is what makes a study checkable (Parker et al., 2016). What the present study adds is a measurement of the same effect when the reader of the method is a machine rather than a person, and the margin is large enough to matter. The two remain complements, in that a specification states what the quantity is, a script demonstrates that it can be computed, and independent execution of that script catches a class of problem that neither addresses on its own (Nüst and Eglen, 2021)."));
c.push(H2("4.2  Agreement between runs is not evidence of correctness"));
c.push(P("The most consequential finding for anyone using these tools is that agreement between runs told you almost nothing about whether they were right. Measured across all twelve tasks, the script produced agreement as often as the specification did, on eleven tasks against eleven, while reaching the correct value far less often. The sharpest instance is the task asking how many rodents were caught in a plot in a year, where all ten runs given a working script returned the same number and none of them was the reference. What they returned was not noise but the reference value of a neighbouring task, so those ten runs computed a quantity exactly right and answered a question nobody had asked. That is reproducibility without validity in its purest form, and it was produced by the practice most often recommended for obtaining reproducibility. It also shows why inspecting the output cannot substitute for stating the quantity, since a number that is correct for some question will look correct for the question in front of you. The two properties are easily conflated (Goodman et al., 2016; Gundersen, 2021), and the checks available to a working ecologist test mostly the first of them. This also inverts what the variability literature leads users to expect, since the measured instability of these models across repeated calls (Ouyang et al., 2023) suggests that disagreement is the thing to watch for. The penguin sex model, where ten runs returned nine different values, is a failure of the same kind as the rodent task in that neither returned the quantity the question intended, but it is the one an ecologist would catch, because scatter announces itself and consensus does not."));
c.push(P("The wrong values were not absurd either, since counting only the plot-years that appear in a file, rather than the plot-years that were surveyed, gives a mean that is a little too high and entirely plausible. Treating each combination of reef, habitat and transect as a survey unit gives a biomass a few per cent below the value the monitoring programme reports. Errors of this size pass review because nothing about them looks wrong, and the history of computational science supplies the pattern. A spreadsheet that silently converted gene names to dates corrupted the supplementary files of roughly a fifth of the genomics papers examined by Ziemann et al. (2016), and a program that transposed two columns produced protein structures that were published, cited and then retracted five times over (Miller, 2006). What the present results add is that a tool which writes the analysis on request can produce errors of this kind on demand, and can produce the same one repeatedly."));
c.push(P("The further sets of runs show that the two remaining checks an ecologist might apply would also have passed. Rewriting the analysis in another language returned the same wrong value on the reef-fish task, so a colleague working in R would have confirmed the Python result. Running the task on five models from three companies returned wrong values from four of them, held consistently within each model, and the two wrong values differed from one another by an order of magnitude, so those models were not disagreeing about precision but computing different quantities and holding to them. A researcher comparing two of them could have found agreement, disagreement, or agreement on a wrong number, according to which two were compared. This is the behaviour anticipated by work on algorithmic monoculture, in which reliance on a small number of systems trained in similar ways causes their errors to coincide rather than to cancel (Kleinberg and Raghavan, 2021). Consulting a second tool is therefore not the independent check it appears to be, and the assumption that it is deserves to be stated and tested rather than relied on."));
c.push(P("Asking for a written report rather than a number showed the sharpest form of the problem, because the conclusions the reports drew were identical in every condition while the numbers behind them were not. The part of an analysis that a reader sees was the part that did not vary. Messeri and Crockett (2024) argue that these tools can generate an illusion of understanding, in which the appearance of a complete and coherent account runs ahead of what has actually been established, and a set of reports agreeing on every conclusion while disagreeing on a quarter of their numbers is a concrete instance of it. A reader has no way of detecting this from the reports alone, which is an argument for keeping the specification and the checks alongside the account rather than treating the account as the product."));
c.push(H2("4.3  Where an instruction was unnecessary"));
c.push(P("Seven of the twelve tasks were answered correctly without any instruction, and this deserves as much emphasis as the tasks where instruction mattered. Where a question has one reading that a competent analyst would adopt, current models adopt it, and a specification adds nothing except a record of what was intended. The effort of writing one is repaid where a question has more than one defensible reading, which is the same place the many-analyst studies find human teams diverging from one another (Silberzahn et al., 2018; Botvinik-Nezer et al., 2020; Breznau et al., 2022; Gould et al., 2025). The four kinds of open choice separate cleanly on this point. Where the question concerned the scope of an estimate the models were already right without help, because the pooled reading the specification asked for is the one they adopted unprompted, whereas where a model had to be fitted they almost never were, because the split of the data, the seed and the scaling were left free and each run settled them differently. That correspondence is useful, because it means the existing catalogues of consequential choices, whether assembled as checklists for analysts (Wicherts et al., 2016) or as the reporting items of a discipline's protocols (Zurell et al., 2020; O'Dea et al., 2021), already indicate where a specification will earn its keep."));
c.push(P("The practical advice that follows is not to specify everything. It is to run an analysis without a specification first, see where repeated runs disagree or where the value differs from an independently computed one, and write the specification against what is found. The four kinds of open choice used here are a workable starting list for that search, and the tasks where instruction changed nothing are as much a part of the result as the tasks where it changed everything."));
c.push(H2("4.4  What a specification needs to contain"));
c.push(P("Two requirements follow from the results, of which the first is to fix the settings that govern any randomness whenever a model is fitted, meaning the split of the data, the seed and the scaling of predictors, since this is where the question alone almost never produced the correct value. The second is to fix the input and the method whenever the sampling unit, the treatment of absent records, the scope of the estimate or the choice of statistic could change the quantity being estimated. Which of the two matters depends on the task, and a specification that fixes neither adds nothing. This is a narrower demand than it may appear, and it has a direct precedent in the checklists of researcher degrees of freedom compiled for the human analyst, which likewise sort the many choices available into the few that change the answer and the many that do not (Wicherts et al., 2016)."));
c.push(P("A specification also has to state what is returned and how close an answer must be to count as the same, because agreement between runs and agreement with a reference are different properties and a set of runs can have the first without the second (Goodman et al., 2016; Gundersen, 2021). This does not mean that every choice should be frozen. Where several readings of a question are defensible, laying them out and reporting the answer under each is the more informative response (Steegen et al., 2016), and a specification is then the record of which reading was taken rather than a claim that the others are wrong. A specification should say which choices define the intended quantity and must be fixed, which may vary, and how any variation that is allowed is to be judged."));
c.push(P("The results also mark the limit of what a specification does. Because it names the quantity rather than the implementation, it survives a change in the names of the columns, which a script does not. Because it still assumes a particular shape of table, it does not survive a rearrangement of the file. There is a third boundary, visible in the runs written in two languages. A specification fixes the quantity but not the estimator, so where the standard libraries of two languages fit a model by different procedures, both can follow the specification exactly and still return different numbers. This is an old result in a new setting, since independent teams implementing one written specification in scientific software were found to diverge from one another by amounts far larger than the authors expected (Hatton and Roberts, 1994). A collection of specifications meant for shared use would therefore need to record the shape of data each one assumes and the language it was written against, and to treat a change in either as calling for a new specification rather than as something the reader will absorb."));
c.push(H2("4.5  Three checks for a shared collection"));
c.push(P("The measures used here become three checks that a shared collection of specifications could apply before accepting one. A repetition check runs the specification several times on fixed data and confirms that the answers agree within the stated tolerance. A reference check compares the answer with a value produced independently. A method check has a separate reader confirm that the analysis followed the method the specification declares. No one of the three stands in for another, since the tasks reported here include cases where runs agreed with one another while none of them matched the reference. A collection that applied only the first check would have accepted those cases. The third of these already exists in a workable form, in the practice of having a named person execute the computations behind a paper before it is published and record what they obtained (Nüst and Eglen, 2021), and the argument here is that a shared collection of specifications should be held to the same standard rather than to a lower one."));
c.push(H2("4.6  Limitations"));
c.push(P("Twelve tasks on four datasets is a small sample of ecological analysis, and although each kind of open choice is represented by three tasks the estimate for each kind rests on those three. Because seven tasks were answered correctly under every condition, the paired tests rest on the six tasks that differ, and the smallest value such a test can return is not far below the values reported. The comparison between the specification and the script also depends on counting runs whose code did not execute, which is stated in the results with the alternatives. For the script against no instruction at all the interval excludes zero while the paired test does not support the difference, because the two use the data differently, the interval resting on the sizes of the twelve differences and the rank test on their signs and order, and with six tasks tied neither has much to work with; we therefore treat that comparison as unsettled and rest nothing on it. Every call that failed at the provider was a call to one of the two companies, so excluding those calls removes runs from one model and not from the other, and three of the thirty six combinations of task and condition are left resting on a single model, one of which is the case where five runs given the question alone agreed on a wrong value. Models from two companies were used in the twelve-task study and from three in the further sets of runs, and behaviour may differ elsewhere. Those further sets rest on four tasks, which is too few to compare conditions in the way the twelve allow, so they are reported as description and carry no test, and the conclusions of this paper would stand without them. The reference values are correct given the quantity each task states, but the choice of quantity is ours, and for a question such as the definition of a survey unit an ecologist could state a different quantity and be right to do so; what the results show is that the value returned without a specification did not match the quantity the question intended, not that one convention is universally correct. The runs that show agreement on a wrong value come from tasks where such agreement is possible, so the frequency of that behaviour across ecological analysis as a whole is not estimated here. The tolerance for each task was fixed before the runs but was chosen by us. Finally, the tasks were single steps rather than multi-step analyses in which one choice feeds the next, and the behaviour of longer workflows was not examined."));
c.push(H2("4.7  Further work"));
c.push(P("The clearest extension is to multi-step analyses, where the number of open choices grows and where an error in an early step is carried forward, and where the first measurements of consistency across longer sequences of tool calls suggest the problem is worse rather than better (Yagubyan, 2026). A second is to widen the range of models, including the smaller ones a research group might run on its own hardware, since the argument about correlated errors between systems bears directly on how much protection a second opinion offers. A third is to test whether specifications written by one group are used correctly by another, which is the property a shared collection depends on and which the present design does not measure. A fourth is to move from tasks with a single number to the assistants now being built for ecological data (Gallois et al., 2025), where the same questions about what has been fixed and what has been left open apply to a whole session rather than to one request. The materials here, including the tasks, the reference values and the procedure for running them, are arranged so that further tasks can be added to the same frame."));

// ---------------- 5 CONCLUSIONS ----------------
c.push(H1("5  Conclusions"));
c.push(P("An analysis described to an artificial-intelligence tool in ordinary words reached the correct value in a little over half of runs, and in one run in fifty where the question left a real choice open. Writing the method down as a specification raised this to nine runs in ten, and did so more effectively than supplying a working script, because a specification states the quantity while a script records the handling of one dataset. On several tasks the runs agreed with one another while being wrong, so neither repetition nor a second model would have exposed the error, which means agreement and correctness have to be established separately. Rewriting the analysis in another language returned the same wrong number, and when the request was for a written report rather than a number, the conclusions the report drew were the same whether or not the numbers behind them were right. Where a question has only one sensible reading a specification adds nothing, and the effort belongs where more than one reading is defensible."));

// ---------------- REFERENCES ----------------
c.push(H1("References"));
const refs = [
  "Baker, M. (2016). 1,500 scientists lift the lid on reproducibility. Nature, 533, 452–454.",
  "Botvinik-Nezer, R., Holzmeister, F., Camerer, C. F., et al. (2020). Variability in the analysis of a single neuroimaging dataset by many teams. Nature, 582, 84–88. https://doi.org/10.1038/s41586-020-2314-9",
  "Breznau, N., Rinke, E. M., Wuttke, A., et al. (2022). Observing many researchers using the same data and hypothesis reveals a hidden universe of uncertainty. Proceedings of the National Academy of Sciences, 119(44), e2203150119. https://doi.org/10.1073/pnas.2203150119",
  "Cooper, N., & the BES Data and Code Hackathon Group. (2026). Data- and code-archiving in the British Ecological Society journals: Present status and recommendations for future improvements. Methods in Ecology and Evolution. https://doi.org/10.1111/2041-210X.70338",
  "Culina, A., van den Berg, I., Evans, S., & Sánchez-Tójar, A. (2020). Low availability of code in ecology: a call for urgent action. PLOS Biology, 18(7), e3000763.",
  "Dorm, F., Millard, J., Purves, D., Harfoot, M., & Mac Aodha, O. (2026). Large language models possess some ecological knowledge, but how much? Ecological Informatics, 103699.",
  "Gallois, E. C., Salili-James, A., Poon, S. T. S., Trebski, A., & Redding, D. W. (2025). Fast-tracking ecological interpretation using bespoke quantitative large language models. Methods in Ecology and Evolution, 16, 2730–2740.",
  "Gelman, A., & Loken, E. (2014). The statistical crisis in science. American Scientist, 102(6), 460. https://doi.org/10.1511/2014.111.460",
  "Goodman, S. N., Fanelli, D., & Ioannidis, J. P. A. (2016). What does research reproducibility mean? Science Translational Medicine, 8(341), 341ps12.",
  "Gould, E., Fraser, H. S., Parker, T. H., Nakagawa, S., et al. (2025). Same data, different analysts: variation in effect sizes due to analytical decisions in ecology and evolutionary biology. BMC Biology, 23, 35. https://doi.org/10.1186/s12915-024-02101-x",
  "Grimm, V., Railsback, S. F., Vincenot, C. E., et al. (2020). The ODD protocol for describing agent-based and other simulation models: a second update to improve clarity, replication, and structural realism. Journal of Artificial Societies and Social Simulation, 23(2), 7. https://doi.org/10.18564/jasss.4259",
  "Gundersen, O. E. (2021). The fundamental principles of reproducibility. Philosophical Transactions of the Royal Society A, 379, 20200210.",
  "Hatton, L., & Roberts, A. (1994). How accurate is scientific software? IEEE Transactions on Software Engineering, 20(10), 785–797. https://doi.org/10.1109/32.328993",
  "He, J., Rungta, M., Koleczek, D., Sekhon, A., Wang, F. X., & Hasan, S. (2024). Does prompt formatting have any impact on LLM performance? arXiv:2411.10541.",
  "Horst, A. M., Hill, A. P., & Gorman, K. B. (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data. R package; data from Gorman, Williams & Fraser (2014), PLOS ONE 9(3), e90081.",
  "Kambouris, S., Wilkinson, D. P., Smith, E. T., & Fidler, F. (2024). Computationally reproducing results from meta-analyses in ecology and evolutionary biology using shared code and data. PLOS ONE, 19(3), e0300333.",
  "Kleinberg, J., & Raghavan, M. (2021). Algorithmic monoculture and social welfare. Proceedings of the National Academy of Sciences, 118(22), e2018340118. https://doi.org/10.1073/pnas.2018340118",
  "Messeri, L., & Crockett, M. J. (2024). Artificial intelligence and illusions of understanding in scientific research. Nature, 627, 49–58. https://doi.org/10.1038/s41586-024-07146-0",
  "Miller, G. (2006). A scientist's nightmare: software problem leads to five retractions. Science, 314(5807), 1856–1857. https://doi.org/10.1126/science.314.5807.1856",
  "Mislan, K. A. S., Heer, J. M., & White, E. P. (2016). Elevating the status of code in ecology. Trends in Ecology & Evolution, 31(1), 4–7. https://doi.org/10.1016/j.tree.2015.11.006",
  "Nüst, D., & Eglen, S. J. (2021). CODECHECK: an open science initiative for the independent execution of computations underlying research articles during peer review to improve reproducibility. F1000Research, 10, 253. https://doi.org/10.12688/f1000research.51738.2",
  "O'Dea, R. E., Lagisz, M., Jennions, M. D., et al. (2021). Preferred reporting items for systematic reviews and meta-analyses in ecology and evolutionary biology: a PRISMA extension (PRISMA-EcoEvo). Biological Reviews, 96, 1695–1722.",
  "Ouyang, S., Zhang, J. M., Harman, M., & Wang, M. (2023). LLM is like a box of chocolates: the non-determinism of ChatGPT in code generation. arXiv:2308.02828.",
  "Parker, T. H., Forstmeier, W., Koricheva, J., et al. (2016). Transparency in ecology and evolution: real problems, real solutions. Trends in Ecology & Evolution, 31(9), 711–719. https://doi.org/10.1016/j.tree.2016.07.002",
  "Sandve, G. K., Nekrutenko, A., Taylor, J., & Hovig, E. (2013). Ten simple rules for reproducible computational research. PLOS Computational Biology, 9(10), e1003285. https://doi.org/10.1371/journal.pcbi.1003285",
  "Silberzahn, R., Uhlmann, E. L., Martin, D. P., et al. (2018). Many analysts, one data set: making transparent how variations in analytic choices affect results. Advances in Methods and Practices in Psychological Science, 1(3), 337–356. https://doi.org/10.1177/2515245917747646",
  "Simmons, J. P., Nelson, L. D., & Simonsohn, U. (2011). False-positive psychology: undisclosed flexibility in data collection and analysis allows presenting anything as significant. Psychological Science, 22(11), 1359–1366. https://doi.org/10.1177/0956797611417632",
  "Steegen, S., Tuerlinckx, F., Gelman, A., & Vanpaemel, W. (2016). Increasing transparency through a multiverse analysis. Perspectives on Psychological Science, 11(5), 702–712. https://doi.org/10.1177/1745691616658637",
  "Wicherts, J. M., Veldkamp, C. L. S., Augusteijn, H. E. M., Bakker, M., van Aert, R. C. M., & van Assen, M. A. L. M. (2016). Degrees of freedom in planning, running, analyzing, and reporting psychological studies: a checklist to avoid p-hacking. Frontiers in Psychology, 7, 1832. https://doi.org/10.3389/fpsyg.2016.01832",
  "Yagubyan, A. (2026). How consistent are LLM agents? Measuring behavioral reproducibility in multi-step tool-calling pipelines. arXiv:2605.28840.",
  "Ziemann, M., Eren, Y., & El-Osta, A. (2016). Gene name errors are widespread in the scientific literature. Genome Biology, 17, 177. https://doi.org/10.1186/s13059-016-1044-7",
  "Zurell, D., Franklin, J., König, C., et al. (2020). A standard protocol for reporting species distribution models (ODMAP). Ecography, 43(9), 1261–1277.",
];
refs.forEach(r => c.push(REFP(r)));

const doc = buildDoc(c, { title: "Specifications and AI data analysis in ecology", footerLeft: "Specifications and AI data analysis in ecology" });
write(doc, path.join(__dirname, "Manuscript_Specifications_AI_Ecology.docx"));
