const T = require("./theme.js");
const { P, TITLE, H1, H2, CAP, TCAP, NUM, REFP, PB, img, table, buildDoc, write } = T;
const path = require("path");
const RES = path.resolve(__dirname, "..", "results");
const RREP = path.resolve(__dirname, "..", "report_reproducibility", "results");

const c = [];

// ---------------- TITLE / ABSTRACT ----------------
c.push(TITLE("Reusable instructions make AI ecological analyses reproducible when they remove analytical choices"));
c.push(P("Article type: Research Article. Target journal: Methods in Ecology and Evolution.", { size: 20, spacing: { after: 20 } }));
c.push(P("This manuscript is prepared for double-anonymous review. Author names, affiliations, the running headline, and all statements (acknowledgements, author contributions, data availability, conflict of interest, and funding) are on the separate title page.", { size: 20 }));

c.push(H1("Abstract"));
c.push(P("1. Scientists increasingly use artificial-intelligence tools to analyse data, yet the same request can return a different answer each time, which makes a result hard to check. One proposed remedy is to write the instructions given to the tool as a reusable skill, much as researchers share analysis code as packages. We asked when a skill makes the answer stable from run to run, and whether a stable answer is also a correct one."));
c.push(P("2. We ran four ecological analyses many times over, under instructions ranging from none to a complete recipe, first in two programming languages and then as whole written reports graded for method by a separate tool. We recorded the running cost each level added, and we repeated the main comparisons on models from three different companies, so the findings would not rest on a single system."));
c.push(P("3. When a task had one obvious method, the tool already returned the same answer without any instruction, so a skill changed little. Instructions mattered in two situations. Where the analysis involved randomness, the answer became stable only once the instruction fixed it. Where a common analytical choice was left open, the repeated runs agreed with one another yet were all wrong, until the instruction fixed the choice. More words alone did not help; only an instruction that removed a specific choice did. The same pattern held in the written reports and across models from different companies, which disagreed without a skill but reached the correct answer with the full one, at little added cost."));
c.push(P("4. Instructions help by removing choices rather than by adding length, and a stable answer is not the same as a correct one, so both must be checked separately. We turn these findings into a proposal for what a shared, reviewed collection of skills should require before accepting one: three checks, that repeated runs agree, that they match a known answer, and that the analysis follows the method it claims. Because each finding rests on a small number of tasks, we offer it as a proposal to be tested rather than a finished standard."));
c.push(P("Data and code for peer review: code, open data, prompts, archival structured outputs, analysis scripts, the cross-provider replication harness and records, document builders, an archive audit, and the proposed manifest schema are provided in an anonymised repository at https://anonymous.4open.science/r/ai-skills-reproducibility-ecology-B13E/README.md. Reef-fish data are available on request. The study repository will be de-anonymised and archived with a DOI on acceptance. A separate public companion registry implementing the proposed community-submission workflow is available in anonymised form at https://anonymous.4open.science/r/scientific-ai-skills-registry-5B70/README.md.", { spacing: { before: 120 } }));
c.push(P("Keywords: agent skills; FAIR; large language models; Model Context Protocol; open science; reproducibility; research software; workflow provenance.", { spacing: { before: 120 } }));
c.push(PB());

// ---------------- 1 INTRODUCTION ----------------
c.push(H1("1  Introduction"));
c.push(P("Science builds on results that other people can reproduce, yet a computed result is often hard to regenerate. In a survey of about 1,500 researchers, more than seven in ten had failed to reproduce another group's result at some point (Baker, 2016). Ecology has the same problem, and it sits mostly in the analysis rather than in the data. Fewer than a fifth of the ecology papers examined by Culina et al. (2020) could be reproduced from the code that came with them, and a recent survey of the journals of the British Ecological Society found that almost every paper shared its data while only about a third shared its code (Cooper and the BES Data and Code Hackathon Group, 2026). Even when the data and the code were both available, one team could reproduce the published result in only a quarter to three-quarters of the cases they tried, depending on how strictly they judged a match (Kambouris et al., 2024)."));
c.push(P("Artificial-intelligence coding tools add a new source of variation on top of this. They are built on models that do not respond identically to the same input, so the same request can produce different code and a different answer on each run, and even a change in how the request is worded or laid out can move a model's performance by a wide margin (He et al., 2024). When a model is allowed to call tools over several steps, the steps it takes and the values it passes to them also vary from one run to the next (Yagubyan, 2026). Ecologists are already beginning to use these tools, from assistants that answer questions about a dataset (Gallois et al., 2025) to tests of how much ecological knowledge a general model holds, which varies a good deal from one task to another (Dorm et al., 2026)."));
c.push(P("One response is to write the procedure that an expert would follow as a set of reusable instructions, which we call a skill. In this paper a skill is a versioned block of instructions that can state which data and columns to use and what to return, the exact method to apply, the settings that fix any randomness, a short list of checks, and how to call any tools. We use the word in this practical sense because the formats offered by different vendors differ in their detail. A skill resembles a software package in that it is meant to be reused and documented, but it is not code that runs on its own, because what it produces still depends on the model that reads it and on the system that runs that model."));
c.push(P("That dependence is what makes the comparison with software packages worth testing. Repositories such as CRAN and Bioconductor accept a package only once it is versioned, documented, and able to pass a set of automated checks, and the FAIR principles for research software set out similar expectations of identity, provenance, and reusable description (Barker et al., 2022). A repository for skills would need evidence of a comparable kind, namely that a skill gives a stable answer, that the answer matches an independently produced reference, and that the analysis really followed the method the skill declares. We found no controlled study in ecology that had separated out which parts of a skill deliver those properties, and that gap is what this paper addresses."));
c.push(P("Throughout the paper we keep apart two ideas that are easily confused (Goodman et al., 2016). The first is whether repeated runs of the same analysis give the same answer, which we call reproducibility. The second is whether that answer matches an independently produced correct value, which we call validity. An analysis can have one without the other, so we always report the two separately. We ask three questions. When does a skill change whether repeated runs agree? Which part of the skill is responsible? And what evidence should a repository require before it accepts a skill?"));

c.push(H2("1.1  What earlier work shows"));
c.push(P("Earlier work points in a consistent direction. Studies of large code archives show that a result reproduces far more often when its code runs inside a complete, recorded computing environment than when it does not (Pimentel et al., 2019; Trisovic et al., 2022). Work on AI agents shows that their reliability has to be judged over many repeated runs and small changes of input rather than from a single success, because the same agent varies from one run to the next (Gupta, 2026; Yagubyan, 2026). A long line of reporting standards in ecology, such as the protocols for species-distribution models and for evidence synthesis, shows that writing the analytical choices down makes a study easier to check and to repeat (O'Dea et al., 2021; Parker et al., 2016; Zurell et al., 2020). And in the study of language models themselves, running the same prompt several times and combining the answers makes the output steadier, although agreement among the runs still does not show that the answer is right (Wang et al., 2023)."));
c.push(P("Two lessons run through this work. Keeping the full record of a run, including its failures, is what lets a result be checked later (Masters et al., 2026), and agreement among runs is necessary for a reliable result but is not enough on its own to make it correct. What this work does not do is take a written instruction apart and test which of its parts actually makes an AI analysis reproducible and correct. That is what we do here. We remove and add the parts of a skill one at a time, measure the effect of each part on both reproducibility and validity, and use the result to say what a repository of skills should require before it admits one. The studies we drew on are listed in Supporting Information S1."));
c.push(PB());

// ---------------- 2 METHODS ----------------
c.push(H1("2  Materials and methods"));
c.push(H2("2.1  What we expected"));
c.push(P("We ran two experiments: the first measured a single number from each analysis, run many times over, so that we could see how often the runs agreed and whether they matched a known correct value; the second raised the unit from a single number to a whole written report with several analyses and a conclusion. We expected that an instruction which fixed a real analytical choice would make the runs agree more often, that adding text without fixing a choice would not, and that agreement and correctness could come apart. We set these expectations out in advance in general terms but did not lodge a formal preregistration, so we treat the statistical tests below as descriptive rather than as confirmatory."));

c.push(H2("2.2  Experiment 1 design"));
c.push(P("The first experiment crossed four analysis tasks, five levels of instruction, and two programming languages, and ran each combination ten times, giving 400 runs in all. Each run was a fresh session of an AI coding tool that read a fixed instruction, wrote and executed Python or R, and returned a single structured result. A run could not see the results of any other run. The instruction and the data were held fixed within each combination, so the differences that remained between runs came from the model and from the code and choices it produced, which is exactly the variation we set out to measure. We therefore treat the runs as repeated executions of one system, not as a sample of every possible model or task."));
c.push(P("Where a method is the same in both languages, the Python and R instructions asked for the same quantity. For the classifier the two languages necessarily differ, because Python used a logistic regression from scikit-learn and R used a binomial generalised linear model with its own way of splitting the data, so the two language versions are a comparison of two reasonable implementations rather than a line-by-line copy of one algorithm."));

c.push(H2("2.3  Tasks and datasets"));
c.push(P("The four tasks were chosen because each contains a point at which a competent analyst could reasonably make a different choice (Table 1). Fixed local files supplied the iris and Palmer Penguins data (Horst et al., 2020). The fourth task used 2,798 reef-fish survey records from ten reefs monitored in Cabo Pulmo National Park, in the Gulf of California, in 2023; these data are restricted and are available on request. For every task we computed a reference value ourselves from the fully specified recipe, and for the reef-fish task the reference also matched the value produced by the monitoring programme's own routine for the same place and year."));
c.push(TCAP("Table 1. The four analysis tasks, the choice each one leaves open, and the reference value we computed. The reference is specific to the implementation where the two languages use different methods."));
c.push(table(
  ["Task", "Dataset (domain)", "Question", "Open choice that can change the answer", "Reference value"],
  [
    ["T1", "iris (botanical)", "Correlation of sepal length and width", "Pooled across species or within each species", "r = −0.1176"],
    ["T2", "Palmer Penguins (ecology)", "Predict sex from four measurements", "Model, data split, random seed, and scaling", "Python 0.8806; R 0.8657"],
    ["T3", "Palmer Penguins (ecology)", "Body-mass difference among species", "Test and effect-size definition", "η² = 0.6697"],
    ["T4", "LTEM reef fish (marine ecology)", "Mean community biomass per transect", "Definition of the survey unit", "3.4642"],
  ],
  [900, 1900, 2400, 2700, 1600]
));

c.push(H2("2.4  Levels of instruction"));
c.push(P("The instruction was the one thing we varied. Starting from a bare request for the answer, each level added to the level before it (Table 2). The first added level gave generic procedural steps but fixed no choice, so it tests whether length alone helps. The next level added an input and method contract that fixed the data to use, the way to handle missing values, and the exact method. The next added fixed settings for any randomness, such as the split and the seed, and for a task with no randomness it simply stated that none was needed. The last level added a short list of checks and a few explicit warnings against known mistakes. Because several tasks already gave the correct answer with no instruction, a lack of difference between the last two levels cannot show that the checks and warnings are useless in general."));
c.push(TCAP("Table 2. The five levels of instruction used in Experiment 1, each building on the one before."));
c.push(table(
  ["Level", "Added content", "What it does"],
  [
    ["C0 none", "Bare task and a request for a structured answer", "The tool's own default"],
    ["C1 basic", "Generic procedural steps", "Adds length without fixing a choice"],
    ["C2 contract", "Input, missing-data, unit, and method contract", "Fixes what is computed"],
    ["C3 controls", "Seed, split, and preprocessing settings", "Fixes the settings for randomness"],
    ["C4 full", "A short check list and explicit warnings", "Adds guard rails"],
  ],
  [1500, 5060, 2800]
));

c.push(H2("2.5  What we measured"));
c.push(P("For each combination of task and instruction level we measured two things across the runs. The first is how often the runs agreed, meaning the share of runs whose answer fell within a small margin, set in advance for that task, of the most common answer. The second is how often a run was correct, meaning the share of runs whose answer fell within that same margin of the reference value, which we had computed ourselves and which no run could see. Reproducibility asks whether the runs agree with one another; validity asks whether they agree with the reference. The margins, the full set of summary measures, and the exact tests are given in Supporting Information S3."));
c.push(P("Because several tasks gave the same answer in every run, the usual tests that compare how spread out the runs are have nothing to work with here. We therefore compared the points at which the results changed as simple proportions, using Fisher's exact test, and we report these as descriptive comparisons among runs rather than as estimates of an effect across all possible tasks. The R runs are reported as a separate check on the Python results."));

c.push(H2("2.6  Experiment 2: whole reports"));
c.push(P("The second experiment raised the unit from a single number to a whole written report on the Palmer Penguins data. A standard report contained four common analyses, and a harder report contained six analyses that each leave a real choice open, in the number of clusters, the way an accuracy is validated, the predictors in a model, the way a confidence interval is formed, the scope of a correlation, and whether to standardise before an ordination. Each report was written under no skill, under a skill that fixed only the sections, and under a full skill that fixed the exact method for every analysis, with eight reports in each case, giving 48 reports. A separate model then read each report and graded how many of the stated methods it had actually used, which is an established way to evaluate model output against a fixed rubric (Zheng et al., 2023). We recorded, for each condition, how many of the required methods a report used, how often independent reports agreed on the numbers, and how often the numbers matched the reference."));
c.push(P("The saved records for this experiment keep the graded numbers and the grades but, because of an oversight in the original workflow, not the full text of each report as the grader saw it, so these grades cannot be re-scored from the archive and we treat this experiment as supporting evidence. The corrected workflow now keeps the full report text and the details of the model that produced and graded it, and the confirmatory design requires this."));

c.push(H2("2.7  The token cost of detail"));
c.push(P("A more detailed skill is a longer instruction, but the same detail also stops the tool from exploring, so whether it costs more overall is not obvious. We measured both sides on one model. The fixed cost is the size of the instruction itself, which we report as a character count and as an approximate token count. The running cost is how much the tool generated on each run, which we recovered from the saved records of the runs. We asked whether a fuller skill changes the total cost, whether it lowers how much the tool generates, and whether a run's cost is any guide to whether it was correct, which it should not be. The measures and tests are given in Supporting Information S8."));

c.push(H2("2.8  Repeating the test on other models and providers"));
c.push(P("To ask whether a skill's effect depends on the model that runs it, we repeated the two most informative levels, no skill and the full skill, on five models spanning three providers, six runs for each task and level. Nothing else changed, so any difference came from the model rather than the task. Within one provider we ran three models of different size, large, medium, and small, through the same setup as the main experiment. To see whether the effect also crossed to other providers, we then ran the strongest widely available model from each of two further providers through a single shared setup in which every model was given the same instruction, returned a complete script, and had that script run in exactly the same way, so that only the model differed. The two setups are described in Supporting Information S9; the shared code-writing setup is deliberately simpler than the first so that models from different providers are compared on equal terms. For each task and level we recorded whether a model's runs agreed, whether they matched the reference, and whether the code ran at all. If independent models all reach the reference under a full skill, then the skill and not the model is deciding the answer; if they do not, the skill is under-specified for that model, which a repository entry would have to state. Provider names are withheld for the anonymised submission and the exact model identifiers are kept with the archived records."));

c.push(H2("2.9  Reproducibility and use of AI"));
c.push(P("The archive holds the instruction generators, the exact instruction files, the scripts that ran the experiments, all 400 single-number records, the 48 report records, the 216 records from the model and token re-run, the 96 records from the cross-provider run, the analysis scripts, the software environment, the scripts that build the figures and this document, an audit script, and the proposed manifest schema. The part of the analysis that is deterministic regenerates every table and figure without running any model, whereas repeating the runs themselves needs the model setup and the restricted reef-fish file. Supporting Information S5 lists the software and data. The oldest single-number records do not store the exact model, its release, or its settings, and we do not try to reconstruct these after the fact; the current workflow refuses to run until those details are supplied and then stores them with every record. The model and token re-run records the model and the amount generated for all of its runs."));
c.push(P("We used an AI model to produce the experimental runs and to help draft the code and the text. The authors read the materials and take responsibility for the analysis and the manuscript. The exact tools used to prepare the manuscript will be listed on the title page before submission."));
c.push(PB());

// ---------------- 3 RESULTS ----------------
c.push(H1("3  Results"));
c.push(P("Every one of the 400 single-number runs returned a value, and all 48 reports and their grades completed. Two of the four tasks, the correlation and the body-mass comparison, gave the reference answer in every run and in both languages, even with no instruction at all. Where the tool already settles on one sensible method, a skill has nothing left to fix, and these two tasks stayed at the correct answer throughout."));
c.push(P("The sex classifier was the only single-number task that varied from run to run. In Python, the three lowest instruction levels agreed on about half of their runs and matched the reference on fewer, so that pooled together they agreed on 16 of 30 runs and were correct on 12 of 30. Once the instruction fixed the split, the random seed, and the scaling, every run returned the same value and every run was correct, at 20 of 20 for both the two highest levels; the change is very unlikely to be chance (Fisher's exact P = 2×10⁻⁴ for agreement). In R the runs agreed a little more often to begin with, at 26 of 30, but none of them matched the R reference until the settings were fixed, after which every run agreed and was correct. Fixing the settings therefore brought each language onto its own reference, though the size of the improvement in agreement differed between the two (Fig. 1A)."));
c.push(P("The reef-fish task separated agreement from correctness in the clearest way. With no instruction or only generic steps, every run in both languages returned about 3.2952 by treating each reef, habitat, and transect combination as the survey unit. The reference recipe treats a reef and transect combination as the unit and returns 3.4642. The runs therefore agreed completely at every level, and yet none of them was correct until the contract fixed the survey unit, after which every run was correct while the agreement stayed at its maximum (Fisher's exact P = 2×10⁻¹⁴). The much larger mistake of averaging the raw records directly, which would give a value about thirty times too low, never occurred; the mistake that did occur was a reasonable-looking difference of about five per cent (Fig. 1B, C)."));
c.push(P("Adding generic steps did not help. For the Python classifier the generic level slightly increased the spread between runs and lowered the share that were correct, because the loose instruction to train a classifier invited a free choice of model and the runs drifted to different settings. Length was not the active part; the fixed choice was. The two fullest levels reached complete agreement and complete correctness on every task, and the added checks and warnings did no harm where they were not the deciding factor."));
c.push(img(path.join(RES, "fig1_binding_transitions.png"), 648, 200, "Where each kind of instruction fixes a different failure"));
c.push(CAP("Figure 1. Different instructions fix different failures, shown for the Python runs, ten per cell. (A) For the sex classifier, agreement and correctness both reach 100% once the instruction fixes the split, seed, and scaling. (B) For reef-fish biomass, the runs agree throughout, but they become correct only when the contract defines the survey unit. (C) The reef-fish values themselves: every run with no or basic instruction sits on a repeatable but wrong value near 3.295, then moves onto the reference of 3.464 once the contract fixes the survey unit, so an analysis can be perfectly repeatable and still wrong. The correlation and body-mass tasks, not shown, stayed at the reference at every level. Shading marks the level at which the deciding instruction is added; the colours are safe for colour-vision deficiency."));

c.push(P("The same two transitions appeared in both languages (Fig. 2). Pooling the classifier runs before and after the settings were fixed, agreement rose from about half to complete in Python and from most to all in R, and correctness rose from part to all in both. For biomass the runs agreed completely before and after the contract in both languages, while correctness rose from none to all. The fully specified classifier still gave two different numbers in the two languages, because the two contracts named two different methods, which is a reminder that a portable skill has to name either one shared algorithm or a separate reference for each language."));
c.push(img(path.join(RES, "fig2_binding_replication.png"), 600, 260, "The same transitions in Python and R"));
c.push(CAP("Figure 2. The same transitions appear in Python and R. Open circles pool the runs before the deciding instruction and filled diamonds pool them after it. For the classifier, before is the three lowest levels (30 runs per language) and after is the two highest (20); for biomass, before is the two lowest levels (20) and after is the three highest (30). Agreement means falling in the most common cluster of answers; correctness means matching the reference for that language."));

c.push(P("The report experiment carried the same lessons up to a whole document (Fig. 3). For the standard report the eight independent runs already produced the same numbers under every condition, so the skill mainly improved how faithfully the report followed the stated methods, from 79% with no skill to 100% with the full skill, and how often the numbers were correct, from 75% to 100%; the deciding difference was again the way the classifier split its data (Fig. 3A). For the harder report, where each analysis leaves a real choice open, agreement itself broke down as well: independent reports agreed on all of their numbers only half of the time, followed the stated methods 58% of the time, and were correct 58% of the time with no skill, and only the full skill brought all three to 100% (Fig. 3B). The disagreement was concentrated in two analyses, the species classifier and the body-mass model, while the clustering analysis agreed but settled on two groups rather than the three the full skill specified (Fig. 3C). This evidence is weaker than the single-number experiment because the graded report text was not kept, so we treat it as support rather than proof."));
c.push(img(path.join(RREP, "fig_hard_report.png"), 648, 193, "Results for the whole reports"));
c.push(CAP("Figure 3. Results for the whole reports, eight reports per condition, graded by one separate model. (A) The standard report with four common analyses and (B) the harder report with six analyses that each leave a choice open, both showing how faithfully the report followed the stated methods, how often independent reports agreed on the numbers, and how often the numbers were correct, under no skill, a structure-only skill, and the full skill. (C) The two numbers that disagreed in the harder report, the species-classifier accuracy and the body-mass model fit; the other six numbers agreed completely under every condition. The full skill reached 100% on every measure shown. The colours are safe for colour-vision deficiency."));

c.push(P("More detail cost a longer instruction but less generation (Supporting Information S8). On one model, the instruction grew from about 219 tokens with no skill to 491 with the full skill, while the amount a run generated fell from a median of 1,983 tokens to 1,254. Pooled across tasks, the lower levels generated more than the higher levels (medians of 1,826 against 1,301), and the full skill generated about 472 fewer tokens per run than no skill (95% interval 60 to 889 fewer). The longer instruction was therefore roughly cancelled by the shorter generation, so on these tasks the gain in reproducibility came at little net cost. Cost was no guide to correctness: runs that missed the reference were more expensive than runs that matched it, not cheaper (medians of 2,382 against 1,345 tokens), so the amount a run generates cannot be read as a sign that it is right."));

c.push(P("The pattern held across models and providers (Fig. 4; Supporting Information S9). We repeated the no-skill and full-skill levels on five models from three providers, six runs each. The correlation and body-mass tasks reached the reference on every model at both levels. On the two harder tasks the no-skill result depended on the model. For the classifier the models returned several different accuracies, and one model's no-skill code failed to run at all in five of its six attempts because it labelled the sexes wrongly and was left with no data. For biomass the no-skill answers ranged from the reference value, through the wrong survey unit, to a value about ten times too large, and four of the five models were wrong, so whether a run with no skill was correct depended on which model happened to run it. Under the full skill every model reached the reference on every task, apart from one model that matched on four of its six biomass runs rather than all six. Two of the five models came from providers that were not used in the main experiment and were run through the simpler setup, so the effect is not tied to one provider or to one way of calling a model. When independent models all reach the reference under a full skill, the skill and not the model is deciding the answer, and the one remaining miss is the kind of model-specific gap a repository entry would need to record."));
c.push(img(path.join(RES, "fig_providers.png"), 648, 230, "Correctness by model at no skill and full skill"));
c.push(CAP("Figure 4. The share of runs that matched the reference, for five models from three providers, at no skill and the full skill, six runs each, for the two harder tasks. Provider 1 is the provider of the main experiment, shown at three model sizes; Providers 2 and 3 are two further providers run through the shared code-writing setup. With no skill, whether a model reached the reference depended on the model, and one model's no-skill code failed to run in most attempts, shown as zero. With the full skill every model reached the reference, apart from Provider 1 (medium) on biomass, which matched on four of six runs. The correlation and body-mass tasks, not shown, were at the reference for every model at both levels."));
c.push(PB());

// ---------------- 4 STANDARD ----------------
c.push(H1("4  From what we found to a standard for a repository"));
c.push(H2("4.1  What the experiments support"));
c.push(P("Two requirements on the content of a skill follow directly from the experiments. The first is to fix the settings for randomness whenever the answer depends on a random split or fit. The second is to fix the input and method contract whenever the scope, the handling of missing data, the way records are combined, the test, the model, or the metric could change the answer. Which of the two matters depends on the task. The experiments also show why every skill needs a clear statement of what it returns and how close is close enough, because agreement and correctness are different things. The checks and warnings in the fullest level did no harm but added nothing measurable beyond the level below on these tasks, where the answer was already correct, so they remain a sensible precaution rather than something we have shown to help."));
c.push(P("Generic steps and section headings are not enough while a real method choice is still open, so a short contract can be more reproducible than a long tutorial. This does not mean that every choice should be frozen. A good skill states which choices define the intended analysis and must be fixed, which choices may vary, and how any allowed variation is judged."));

c.push(H2("4.2  What a skill should have to show"));
c.push(P("We propose a first version of a Skill Evidence Manifest, provided in the repository as a schema with a worked example. It separates the requirements the experiments support from the further requirements drawn from the FAIR principles for research software and from current practice in evaluating agents (Barker et al., 2022; Masters et al., 2026). A candidate entry states:"));
c.push(NUM("Identity and provenance: a stable name, a version, the authors, the licence, the source study, the skill file, the range of models and systems it was made for, and its known limits."));
c.push(NUM("The input, method, and output contract: the data and columns it needs, the rule for missing data, the quantity it returns, the exact method, the type and unit of the output, and a margin justified on scientific grounds."));
c.push(NUM("Settings and environment: the settings for randomness, the scope of any preprocessing, the language, the package versions, the tools, and any reference that is specific to one implementation."));
c.push(NUM("Evidence: how many repeated runs are required, the reference values to test against, the rubric for checking the method, the full records of the runs, the failures and retries, and signed summaries for the version submitted."));
c.push(NUM("Cost and compatibility, which are optional: the size of the instruction and a typical running cost, and the models the skill was checked on with whether each reached the reference, which together form a record of where the skill is known to work."));
c.push(P("The repository's checker confirms that the manifest is complete and well formed, that the files it names exist, that the margins are positive, that enough repeated runs are required, and that a skill with randomness fixes its settings. That checker confirms that the description is complete, not that the science is right, so a human reviewer still has to judge the quantity, the reference, the margin, and whether the skill suits the stated field."));
c.push(P("We have released a public version of this, the Scientific AI Skills Registry (version 0.1.0; anonymised for review at https://anonymous.4open.science/r/scientific-ai-skills-registry-5B70/README.md). Contributors propose a versioned skill by pull request, and an automated check reads the manifest, confirms the local files, the declared settings, the evidence, the provenance, the licence, and the safety of the file paths, and confirms that the index is consistent, all without running the submitted code. Passing these checks shows only that the entry is complete; whether the science is right and whether the skill belongs in the collection stay human decisions."));

c.push(H2("4.3  Three separate checks"));
c.push(P("The measures we used become three checks a repository can run. A self-consistency check runs the skill several times on fixed data and confirms that the answers agree within the stated margin. A reference check compares each answer with a value produced independently. A coherence check has a separate reader confirm that the finished analysis used the method the skill declares. No one check stands in for another: the reef-fish skill passed the first while failing the second, and the report experiment showed that an analysis can be complete in form and still not follow its stated method. Because the coherence grades here came from a single reader and cannot be re-scored, a working repository should prefer automatic checks where it can, keep the graded output, and use several independent readers where a judgement of method is needed."));
c.push(PB());

// ---------------- 5 DISCUSSION ----------------
c.push(H1("5  Discussion"));
c.push(H2("5.1  A conditional effect, not a blanket one"));
c.push(P("The main result is a conditional one. Within one setup, a skill changed the answer when it removed a choice that mattered, and not otherwise. It did nothing for tasks that were already correct without it, and generic extra text did not steady the classifier. The right reading is therefore not that skills make AI reproducible in general, but that an explicit contract can control the specific choices that would otherwise make an analysis wander. The same freedom is well documented for human analysts, where reasonable but unstated choices open a garden of forking paths along which a defensible analysis can be led to many different results (Simmons et al., 2011; Gelman & Loken, 2014), and where laying those choices out as a multiverse shows how far the answer can move (Steegen et al., 2016); a skill is one way to close the choices in advance rather than after the fact. This makes skill design a task one can test: list the choices a task leaves open, fix the ones that define the intended analysis, and check the answer over repeated runs."));
c.push(P("The warnings in the fullest level carry a related lesson. Our warnings forbade a crude mistake, averaging the raw records, that would have given a biomass about thirty times too low, and no run ever made it. The mistake every unconstrained run did make, a reasonable but non-standard survey unit, was fixed by the contract rather than by any warning. A warning guards only the mistake it names, and a capable model tends to avoid the obvious blunder while still making the defensible-looking choice that was left open, and to make it in the same way every time. Warnings are therefore most useful when they are written against the mistakes an analysis really attracts, which are best found by running the task without a skill and seeing where it goes, rather than against the mistakes that are easiest to imagine. This is also why the warnings showed no benefit here: they addressed a mistake the models never made."));

c.push(H2("5.2  Repeatable, correct, and portable are three different things"));
c.push(P("The reef-fish task is the clearest warning. Two languages and twenty runs before the contract all agreed on the same non-reference answer. Agreement between independent runs, and even between two languages, is evidence that an answer is stable, but not that it is right (Goodman et al., 2016; Gundersen, 2021). The classifier makes the opposite point: after its settings were fixed each language matched its own reference but the two languages still gave different numbers, because their contracts named different methods. A repository therefore has to keep the quantity, the method, the implementation, and the reference together as one versioned unit, and a skill meant to be portable needs either a method specified at the level of the algorithm or an explicit claim of equivalence that has been tested across implementations."));

c.push(H2("5.3  From single numbers to whole reports"));
c.push(P("The report experiment suggests that a method contract matters more as the number of open choices grows. Fixing only the structure did not fix the statistics, whereas a full contract brought all six of the harder report's analyses into agreement and removed the disagreement in the numbers. This evidence is weaker than the single-number experiment because only the numbers and the grades survive. The corrected workflow is itself a useful result: a repository has to keep the output that a reader graded, the rubric, the details of the grader, the history of retries, and any runs left out, because otherwise the coherence check cannot be repeated."));

c.push(H2("5.4  Cost, and other models"));
c.push(P("Two further results bear on how a repository would describe a skill. The first is that detail was close to free. A fuller skill is a longer instruction, but the same detail that fixes the analysis also stops the model exploring, so the longer instruction was roughly cancelled by the shorter generation, and the gain in reproducibility carried no large cost in these tasks. A repository could record the size of an instruction and a typical running cost as part of its entry, the way a package records its size and its dependencies, so that a user can weigh the cost of using it. That the failed runs were the more expensive ones also means cost cannot stand in for quality; a skill still has to be checked against a reference."));
c.push(P("The second is that the effect did not depend on the particular model or provider, which is the property a shared repository most needs. With no skill, five models from three providers disagreed with one another and with the reference on the two harder tasks, some by a wide margin, and one model's code did not run at all, so an analysis with no skill was partly a matter of which model happened to run it. This mirrors a pattern well documented for people, where many independent teams given the same data and question reach different results through defensible but different analytical choices (Silberzahn et al., 2018; Botvinik-Nezer et al., 2020; Breznau et al., 2022), a spread now shown for ecological and evolutionary data as well (Gould et al., 2025); here the differing analysts are differing models. The full skill removed almost all of this and brought the models onto the reference, including two models from providers not used in the main experiment and run through a different and simpler setup, which shows the effect is not a quirk of one provider or one way of calling a model. The single case in which a model still missed on a third of its runs is the exception that makes the point: a repository cannot assume that a skill which works on one model works on all, so it should record the models and providers a skill was checked on and treat agreement across them as something to be shown rather than assumed. These two analyses are supporting evidence and share the limits of the main experiment."));

c.push(H2("5.5  Limitations"));
c.push(P("The main experiment used four single-number tasks, three datasets, two languages, and ten runs each, and the report experiment used one dataset, two report templates, eight reports per condition, and a single grader. The effect of fixing randomness rests on the classifier alone and the effect of the contract rests on the reef-fish task alone, so each rests on one task rather than on a sample of tasks. Two of the four tasks were already correct without a skill, which limits how much they can show about the finer parts of a skill. The margins were fixed in the analysis code but not in advance, and the tests compare pooled runs and are descriptive. The correctness score for the reports depends on the references we chose, some of which stand for a defensible choice rather than a single truth. The cost result comes from one model and setup. The test on other models covered five models and three providers but used six runs each and, for the two extra providers, the simpler code-writing setup rather than the setup of the main experiment, so a fully matched comparison across providers is left to the confirmatory study."));
c.push(P("The oldest single-number records do not store the exact model, its release, or its settings, so although the instructions and the answers are kept, the model layer of those runs cannot be reconstructed exactly. The report records do not keep the graded text. The reef-fish data are restricted, so the later analysis can be reproduced from the saved summaries but that one task cannot be re-run end to end from open data. These limits keep the claim tied to the systems and tasks we used."));

c.push(H2("5.6  The study that would settle it"));
c.push(P("A confirmatory study should fix its tasks, comparisons, exclusion rules, and margins in advance, include at least two tasks for each kind of open choice, use at least twenty runs for each combination, and cover several fixed model versions and providers under one setup, keeping the full record of every run and blinding several graders. It should include tasks where a common default is plausible but wrong, and it should treat the tasks and the models as samples from defined groups, so that the result speaks to those groups and not only to the particular cases. Above all it should test whether the three checks, measured on one set of tasks, predict that a skill stays reproducible and correct on tasks it was not tuned on, which is the test of the standard itself. The manifest and its checker give a ready protocol for that study and a working entry format for a first repository."));

// ---------------- 6 CONCLUSIONS ----------------
c.push(H1("6  Conclusions"));
c.push(P("A skill did not have a single, uniform effect. In these tasks it mattered when it removed a choice that would otherwise change the answer: fixing the settings for randomness brought a classifier onto its reference, and an input and method contract corrected a biomass result that was perfectly repeatable and yet wrong. Agreement, correctness, and faithfulness to the stated method therefore have to be checked separately. The case for a repository follows as a claim that can be tested: publish each skill together with its contract, its settings, the full records of its runs, its reference values, its margins, and the evidence that it followed its method, and turn away any entry that fails a check. The included manifest turns that case into something a repository can run. What is needed next is a preregistered test across several models before it can be treated as a settled standard for AI analysis in ecology."));

// ---------------- REFERENCES ----------------
c.push(H1("References"));
const refs = [
  "Baker, M. (2016). 1,500 scientists lift the lid on reproducibility. Nature, 533, 452–454.",
  "Barker, M., Chue Hong, N. P., Katz, D. S., et al. (2022). Introducing the FAIR Principles for research software. Scientific Data, 9, 622.",
  "Botvinik-Nezer, R., Holzmeister, F., Camerer, C. F., et al. (2020). Variability in the analysis of a single neuroimaging dataset by many teams. Nature, 582, 84–88. https://doi.org/10.1038/s41586-020-2314-9",
  "Breznau, N., Rinke, E. M., Wuttke, A., et al. (2022). Observing many researchers using the same data and hypothesis reveals a hidden universe of uncertainty. Proceedings of the National Academy of Sciences, 119(44), e2203150119. https://doi.org/10.1073/pnas.2203150119",
  "Cooper, N., & the BES Data and Code Hackathon Group. (2026). Data- and code-archiving in the British Ecological Society journals: Present status and recommendations for future improvements. Methods in Ecology and Evolution. https://doi.org/10.1111/2041-210X.70338",
  "Culina, A., van den Berg, I., Evans, S., & Sánchez-Tójar, A. (2020). Low availability of code in ecology: a call for urgent action. PLOS Biology, 18(7), e3000763.",
  "Dorm, F., Millard, J., Purves, D., Harfoot, M., & Mac Aodha, O. (2026). Large language models possess some ecological knowledge, but how much? Ecological Informatics, 103699.",
  "Gallois, E. C., Salili-James, A., Poon, S. T. S., Trebski, A., & Redding, D. W. (2025). Fast-tracking ecological interpretation using bespoke quantitative large language models. Methods in Ecology and Evolution, 16, 2730–2740.",
  "Gelman, A., & Loken, E. (2014). The statistical crisis in science. American Scientist, 102(6), 460. https://doi.org/10.1511/2014.111.460",
  "Goodman, S. N., Fanelli, D., & Ioannidis, J. P. A. (2016). What does research reproducibility mean? Science Translational Medicine, 8(341), 341ps12.",
  "Gould, E., Fraser, H. S., Parker, T. H., Nakagawa, S., et al. (2025). Same data, different analysts: variation in effect sizes due to analytical decisions in ecology and evolutionary biology. BMC Biology, 23, 35. https://doi.org/10.1186/s12915-024-02101-x",
  "Gundersen, O. E. (2021). The fundamental principles of reproducibility. Philosophical Transactions of the Royal Society A, 379, 20200210.",
  "Gupta, A. (2026). ReliabilityBench: Evaluating LLM agent reliability under production-like stress conditions. arXiv:2601.06112.",
  "He, J., Rungta, M., Koleczek, D., Sekhon, A., Wang, F. X., & Hasan, S. (2024). Does prompt formatting have any impact on LLM performance? arXiv:2411.10541.",
  "Horst, A. M., Hill, A. P., & Gorman, K. B. (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data. R package; data from Gorman, Williams & Fraser (2014), PLOS ONE 9(3), e90081.",
  "Kambouris, S., Wilkinson, D. P., Smith, E. T., & Fidler, F. (2024). Computationally reproducing results from meta-analyses in ecology and evolutionary biology using shared code and data. PLOS ONE, 19(3), e0300333.",
  "Masters, C., Liu, Z., & Albrecht, S. V. (2026). Rollout Cards: A reproducibility standard for agent research. arXiv:2605.12131.",
  "O'Dea, R. E., Lagisz, M., Jennions, M. D., et al. (2021). Preferred reporting items for systematic reviews and meta-analyses in ecology and evolutionary biology: a PRISMA extension (PRISMA-EcoEvo). Biological Reviews, 96, 1695–1722.",
  "Parker, T. H., Forstmeier, W., Koricheva, J., et al. (2016). Transparency in ecology and evolution: real problems, real solutions. Trends in Ecology & Evolution, 31(9), 711–719. https://doi.org/10.1016/j.tree.2016.07.002",
  "Pimentel, J. F., Murta, L., Braganholo, V., & Freire, J. (2019). A large-scale study about quality and reproducibility of Jupyter notebooks. MSR 2019.",
  "Silberzahn, R., Uhlmann, E. L., Martin, D. P., et al. (2018). Many analysts, one data set: making transparent how variations in analytic choices affect results. Advances in Methods and Practices in Psychological Science, 1(3), 337–356. https://doi.org/10.1177/2515245917747646",
  "Simmons, J. P., Nelson, L. D., & Simonsohn, U. (2011). False-positive psychology: undisclosed flexibility in data collection and analysis allows presenting anything as significant. Psychological Science, 22(11), 1359–1366. https://doi.org/10.1177/0956797611417632",
  "Steegen, S., Tuerlinckx, F., Gelman, A., & Vanpaemel, W. (2016). Increasing transparency through a multiverse analysis. Perspectives on Psychological Science, 11(5), 702–712. https://doi.org/10.1177/1745691616658637",
  "Trisovic, A., Lau, M. K., Pasquier, T., & Crosas, M. (2022). A large-scale study on research code quality and execution. Scientific Data, 9, 60.",
  "Wang, X., Wei, J., Schuurmans, D., et al. (2023). Self-consistency improves chain-of-thought reasoning in language models. ICLR 2023.",
  "Yagubyan, A. (2026). How consistent are LLM agents? Measuring behavioral reproducibility in multi-step tool-calling pipelines. arXiv:2605.28840.",
  "Zheng, L., Chiang, W.-L., Sheng, Y., Zhuang, S., Wu, Z., Zhuang, Y., Lin, Z., Li, Z., Li, D., Xing, E. P., Zhang, H., Gonzalez, J. E., & Stoica, I. (2023). Judging LLM-as-a-judge with MT-Bench and Chatbot Arena. Advances in Neural Information Processing Systems, 36, 46595–46623.",
  "Zurell, D., Franklin, J., König, C., et al. (2020). A standard protocol for reporting species distribution models (ODMAP). Ecography, 43(9), 1261–1277.",
];
refs.forEach(r => c.push(REFP(r)));

const doc = buildDoc(c, { title: "AI skills and output reproducibility in ecology (MEE manuscript)", footerLeft: "AI analysis skills and reproducible ecology" });
write(doc, path.join(__dirname, "Manuscript_AI_Skills_Reproducibility_MEE.docx"));
